function exportPath = exportReport(report, outputDir, format)
% EXPORTREPORT Exports clinical screening report to file
%
% Syntax:
%   exportPath = exportReport(report)
%   exportPath = exportReport(report, outputDir, 'txt')
%   exportPath = exportReport(report, outputDir, 'html')
%
% EyeXpert — SIH 2026

    arguments
        report (1,1) struct
        outputDir (1,1) string = fullfile(fileparts(mfilename('fullpath')), '..', 'reports')
        format (1,1) string = "txt"
    end

    if ~isfolder(outputDir)
        mkdir(outputDir);
    end

    cleanId = regexprep(report.ImageId, '[^\w\-\.]', '_');
    timestampStr = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));

    if format == "html"
        filename = sprintf('EyeXpert_Report_%s_%s.html', cleanId, timestampStr);
        exportPath = fullfile(outputDir, filename);
        
        htmlContent = sprintf([ ...
            '<!DOCTYPE html><html><head><meta charset="utf-8">' ...
            '<title>EyeXpert Screening Report - %s</title>' ...
            '<style>' ...
            'body { font-family: "Segoe UI", Arial, sans-serif; margin: 30px; background: #f8fafc; color: #1e293b; }' ...
            '.report-card { max-width: 800px; margin: 0 auto; background: #ffffff; padding: 30px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); border: 1px solid #e2e8f0; }' ...
            'h1 { color: #0f172a; margin-bottom: 5px; font-size: 24px; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }' ...
            '.meta { color: #64748b; font-size: 14px; margin-bottom: 20px; }' ...
            '.section { margin: 20px 0; padding: 15px; border-radius: 8px; background: #f1f5f9; }' ...
            '.badge-referable { display: inline-block; padding: 4px 10px; border-radius: 20px; font-weight: bold; background: #fee2e2; color: #b91c1c; }' ...
            '.badge-nonref { display: inline-block; padding: 4px 10px; border-radius: 20px; font-weight: bold; background: #dcfce7; color: #15803d; }' ...
            '.disclaimer { font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; margin-top: 25px; padding-top: 12px; font-style: italic; }' ...
            '</style></head><body>' ...
            '<div class="report-card">' ...
            '<h1>EYEXPERT — CLINICAL SCREENING REPORT</h1>' ...
            '<div class="meta">SIH 2026 Telemedicine Decision Support | Timestamp: %s | Image ID: <b>%s</b></div>' ...
            '<div class="section"><h3>1. Image Quality Assessment</h3>' ...
            '<p><b>Status:</b> %s | <b>Score:</b> %s | <b>Enhancement:</b> %s</p></div>' ...
            '<div class="section"><h3>2. DR AI Classification</h3>' ...
            '<p><b>Grade:</b> %s (%s)</p>' ...
            '<p><b>Referable DR:</b> <span class="%s">%s</span></p>' ...
            '<p><b>Model Probability:</b> %s | <b>Calibrated Confidence:</b> %s</p></div>' ...
            '<div class="section"><h3>3. Clinical Recommendation</h3>' ...
            '<p>%s</p></div>' ...
            '<div class="section"><h3>4. Human Clinical Validation</h3>' ...
            '<p><b>Status:</b> %s | <b>Notes:</b> %s</p></div>' ...
            '<div class="disclaimer"><b>Clinical Notice:</b> %s</div>' ...
            '</div></body></html>' ...
        ], report.ImageId, report.Timestamp, report.ImageId, ...
           report.QualityStatus, report.QualityScore, report.EnhancementStatus, ...
           report.DRLevel, report.Severity, ...
           ternary(contains(report.ReferableDR, "YES"), "badge-referable", "badge-nonref"), ...
           report.ReferableDR, report.ModelProbability, report.CalibratedConfidence, ...
           report.Recommendation, report.HumanValidationStatus, report.ClinicianNotes, ...
           report.Disclaimer);

        fid = fopen(exportPath, 'w');
        fprintf(fid, '%s', htmlContent);
        fclose(fid);

    else
        filename = sprintf('EyeXpert_Report_%s_%s.txt', cleanId, timestampStr);
        exportPath = fullfile(outputDir, filename);
        fid = fopen(exportPath, 'w');
        fprintf(fid, '%s', report.TextReport);
        fclose(fid);
    end

    fprintf('Screening report exported to: %s\n', exportPath);
end

function val = ternary(cond, a, b)
    if cond
        val = a;
    else
        val = b;
    end
end
