class AppLanguage {
  final String code;
  final String name;
  final String localName;
  final String flag;

  const AppLanguage({
    required this.code,
    required this.name,
    required this.localName,
    required this.flag,
  });
}

class AppLocalizations {
  static const List<AppLanguage> supportedLanguages = [
    AppLanguage(code: 'en', name: 'English', localName: 'English', flag: '🇬🇧'),
    AppLanguage(code: 'hi', name: 'Hindi', localName: 'हिन्दी', flag: '🇮🇳'),
    AppLanguage(code: 'mr', name: 'Marathi', localName: 'मराठी', flag: '🇮🇳'),
    AppLanguage(code: 'gu', name: 'Gujarati', localName: 'ગુજરાતી', flag: '🇮🇳'),
    AppLanguage(code: 'ta', name: 'Tamil', localName: 'தமிழ்', flag: '🇮🇳'),
  ];

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Drishti',
      'tagline': 'Explainable AI Retinal Screening for Rural India',
      'phc_screener': 'PHC SCREENER',
      'specialist': 'OPHTHALMOLOGY SPECIALIST',
      'switch_to_doctor': 'Switch to Doctor',
      'switch_to_screener': 'Switch to Screener',
      'audio_guide': 'Audio Guide',
      'audio_on': 'Voice Guide On',
      'audio_off': 'Voice Guide Off',
      
      // 3-Step Guided Flow Ribbon
      'step1_ribbon': '1. Patient Intake & Context',
      'step2_ribbon': '2. Capture Retinal Image',
      'step3_ribbon': '3. Result & Referral Slip',

      // Navigation
      'nav_dashboard': 'Dashboard',
      'nav_intake': 'New Intake',
      'nav_patients': 'Patients',
      'nav_sync': 'Rural Sync',
      'nav_profile': 'Profile',
      'nav_queue': 'Review Queue',
      'nav_cases': 'All Cases',
      'nav_overview': 'Overview',
      'nav_reports': 'Reports',

      // Dashboard
      'greeting_morning': 'Good morning',
      'greeting_afternoon': 'Good afternoon',
      'greeting_evening': 'Good evening',
      'stat_screened': 'Total Screened',
      'stat_screened_sub': 'Total patient intake',
      'stat_referable': 'AI Referable',
      'stat_referable_sub': 'Flagged for specialist',
      'stat_pending': 'Awaiting Review',
      'stat_pending_sub': 'In specialist queue',
      'stat_completed': 'Finalized',
      'stat_completed_sub': 'Diagnoses confirmed',
      'start_screening': 'START NEW SCREENING',
      'view_records': 'View Patient Records',
      'recent_screenings': 'Recent Screenings',
      'view_all': 'View All',
      'quick_demo_test': '⚡ Instant Clinical Test Samples',
      'quick_demo_desc': 'Test any DR stage instantly without physical camera',

      // Intake
      'patient_demographics': 'PATIENT DEMOGRAPHICS',
      'patient_id': 'Patient ID / Screening Token',
      'age': 'Age (Years)',
      'gender': 'Gender',
      'gender_female': 'Female',
      'gender_male': 'Male',
      'gender_other': 'Other',
      'diabetes_duration': 'Diabetes Duration (Years)',
      'eye_selection': 'EXAMINATION EYE',
      'right_eye': 'RIGHT EYE (OD)',
      'left_eye': 'LEFT EYE (OS)',
      'od_subtitle': 'Right Eye • Oculus Dexter',
      'os_subtitle': 'Left Eye • Oculus Sinister',
      'proceed_capture': 'Proceed to Retinal Capture',
      'fill_demo': '⚡ Fill Demo Patient',

      // Capture
      'retinal_acquisition': 'Retinal Fundus Image Acquisition',
      'camera_capture': 'Capture with Camera',
      'gallery_select': 'Select from File',
      'reticle_guide': 'Center optic disc & macula inside reticle guide',
      'loaded_guide': 'Retinal Image Loaded • Inspect Retinal FOV',
      'clinical_samples_title': 'CLINICAL TEST SAMPLES (SIH 2026 BENCHMARK)',
      'confirm_quality': 'Confirm & Evaluate Image Quality',
      'reset': 'Reset',
      'optical_checklist_title': 'Camera Photo Quality Check:',
      'chk_clarity': 'Focus & Sharpness: Clear',
      'chk_light': 'Lighting & Exposure: Adequate',
      'chk_center': 'Field of View: Centered',
      'speak_guidance': 'Speak Guidance to Patient',

      // Quality
      'quality_title': 'Optical Quality Safety Gate',
      'sharpness': 'Focus & Sharpness',
      'illumination': 'Illumination & Exposure',
      'fov': 'Field of View Coverage',
      'quality_good': 'GOOD QUALITY',
      'quality_borderline': 'BORDERLINE (ENHANCED)',
      'quality_ungradable': 'UNGRADABLE — RETAKE REQUIRED',
      'proceed_inference': 'Proceed to AI Diagnostic Inference',
      'retake_image': 'Recapture Retinal Photograph',

      // Results
      'ai_result_title': 'AI Decision Support Assessment',
      'level_0': 'No Diabetic Retinopathy',
      'level_1': 'Mild NPDR',
      'level_2': 'Moderate NPDR',
      'level_3': 'Severe NPDR',
      'level_4': 'Proliferative DR (Urgent)',
      'referable_yes': 'REFERRAL REQUIRED',
      'referable_no': 'NON-REFERABLE (ROUTINE)',
      'view_xai': 'View Explainable AI (Grad-CAM)',
      'view_report': 'View Clinical Report & Slip',
      'new_screening': 'Start Next Patient',
      'patient_slip_btn': 'Patient Referral Slip',

      // Explainability
      'xai_title': 'Visual Explainability (Grad-CAM)',
      'tab_original': 'ORIGINAL',
      'tab_gradcam': 'GRAD-CAM',
      'tab_overlay': 'OVERLAY',
      'blend_opacity': 'Overlay Blend:',
      'lesion_guide_title': 'RETINAL LESION & BIOMARKER GUIDE',
      'attended_structures': 'Model-Attended Retinal Zones',

      // Report & Referral Slip
      'referral_card_title': 'Patient Referral & Advice Card',
      'slip_title': 'DRISHTI — Tele-Retinal Screening & Referral Slip',
      'slip_subtitle': 'National Programme for Control of Blindness (NPCB) Support | SIH 2026',
      'slip_verified_title': 'DISTRICT TELE-OPHTHALMOLOGY VERIFIED',
      'slip_urgency_urgent': 'URGENT SPECIALIST REFERRAL REQUIRED',
      'slip_urgency_routine': 'NO SIGHT-THREATENING RETINOPATHY',
      'slip_advice_urgent': 'Hospital Instructions: Signs of diabetic vascular changes detected. Please consult an ophthalmologist at the district hospital within 7–14 days.',
      'slip_advice_routine': 'Clinical Advice: No immediate diabetic retinal lesions detected. Maintain strict blood sugar control and repeat annual screening in 12 months.',
      'slip_tips_title': 'Key Health Guidance for Patient and Family:',
      'slip_tip1_title': '1. Blood Sugar Control (HbA1c < 7.0%)',
      'slip_tip1_desc': 'Take medications/insulin on schedule. Maintain 3-month HbA1c below 7.0%.',
      'slip_tip2_title': '2. Blood Pressure Control (< 130/80 mmHg)',
      'slip_tip2_desc': 'Hypertension accelerates microvascular retinal leakage and hemorrhages.',
      'slip_tip3_title': '3. Balanced Diabetic Diet',
      'slip_tip3_desc': 'Eat green leafy vegetables, whole grains, and drink adequate water. Avoid refined sugars.',
      'slip_tip4_title': '4. Annual Retinal Examination',
      'slip_tip4_desc': 'Diabetic retinopathy causes no pain in early stages. Regular AI screening preserves sight.',
      'slip_footer_doc': 'Verified Tele-Ophthalmologist: Dr. Rajesh Kumar, MD (Ophthalmology)',
      'slip_footer_notice': '*This is a computer-verified tele-screening slip. No physical signature is required.',
      'slip_qr_label': 'QR Verify',
      'slip_print_btn': 'Print Referral Slip',
      'slip_share_btn': 'Share via WhatsApp',
      'urgency_immediate': 'URGENT: Consult Ophthalmologist within 7–14 days',
      'urgency_routine': 'ROUTINE: Annual Dilated Retinal Screening in 12 months',
      'advice_hba1c': 'Keep HbA1c below 7.0% with physician consultation',
      'advice_bp': 'Monitor blood pressure regularly (target < 130/80 mmHg)',
      'advice_diet': 'Follow balanced low-glycemic diabetic diet',
      'print_pdf': 'Download PDF Slip',
      'share_slip': 'Share via WhatsApp',
    },

    'hi': {
      'app_title': 'दृष्टि (Drishti)',
      'tagline': 'ग्रामीण भारत के लिए व्याख्यात्मक एआई रेटिना जांच',
      'phc_screener': 'प्राथमिक स्वास्थ्य कार्यकर्ता (PHC)',
      'specialist': 'नेत्र रोग विशेषज्ञ',
      'switch_to_doctor': 'डॉक्टर पोर्टल पर जाएं',
      'switch_to_screener': 'स्वास्थ्य कार्यकर्ता पोर्टल',
      'audio_guide': 'आवाज सहायता',
      'audio_on': 'ध्वनि मार्गदर्शन सक्रिय',
      'audio_off': 'ध्वनि मार्गदर्शन बंद',

      // 3-Step Guided Flow Ribbon
      'step1_ribbon': '1. मरीज विवरण दर्ज करें (Intake)',
      'step2_ribbon': '2. रेटिना फोटो लें (Photo)',
      'step3_ribbon': '3. सरल परिणाम और पर्ची (Result & Slip)',

      // Navigation
      'nav_dashboard': 'डैशबोर्ड',
      'nav_intake': 'नई जांच',
      'nav_patients': 'मरीज सूची',
      'nav_sync': 'ग्रामीण सिंक',
      'nav_profile': 'प्रोफ़ाइल',
      'nav_queue': 'समीक्षा कतार',
      'nav_cases': 'सभी मामले',
      'nav_overview': 'सिंहावलोकन',
      'nav_reports': 'रिपोर्ट्स',

      // Dashboard
      'greeting_morning': 'शुभ प्रभात',
      'greeting_afternoon': 'शुभ दोपहर',
      'greeting_evening': 'शुभ संध्या',
      'stat_screened': 'कुल जांचे गए',
      'stat_screened_sub': 'पंजीकृत मरीज',
      'stat_referable': 'रेफरल योग्य',
      'stat_referable_sub': 'डॉक्टर के लिए चिह्नित',
      'stat_pending': 'समीक्षा लंबित',
      'stat_pending_sub': 'विशेषज्ञ कतार में',
      'stat_completed': 'सत्यापित',
      'stat_completed_sub': 'निदान पूर्ण हुआ',
      'start_screening': '+ नई रेटिना जांच शुरू करें',
      'view_records': 'मरीज रिकॉर्ड देखें',
      'recent_screenings': 'हाल की जांचें',
      'view_all': 'सभी देखें',
      'quick_demo_test': '⚡ त्वरित क्लिनिकल परीक्षण नमूने',
      'quick_demo_desc': 'बिना कैमरे के किसी भी चरण की तत्काल जांच करें',

      // Intake
      'patient_demographics': 'मरीज का विवरण',
      'patient_id': 'मरीज आईडी / टोकन नंबर',
      'age': 'आयु (वर्ष)',
      'gender': 'लिंग',
      'gender_female': 'महिला',
      'gender_male': 'पुरुष',
      'gender_other': 'अन्य',
      'diabetes_duration': 'मधुमेह की अवधि (वर्ष)',
      'eye_selection': 'जांच हेतु आंख चुनें',
      'right_eye': 'दाहिनी आंख (OD)',
      'left_eye': 'बायीं आंख (OS)',
      'od_subtitle': 'दाहिनी आंख • Oculus Dexter',
      'os_subtitle': 'बायीं आंख • Oculus Sinister',
      'proceed_capture': 'रेटिना फोटो लेने के लिए आगे बढ़ें',
      'fill_demo': '⚡ डेमो मरीज का विवरण भरें',

      // Capture
      'retinal_acquisition': 'रेटिनल फंडस फोटो अधिग्रहण',
      'camera_capture': 'कैमरे से फोटो लें',
      'gallery_select': 'गैलरी / फाइल से चुनें',
      'reticle_guide': 'ऑप्टिक डिस्क और मैकुला को केंद्र में रखें',
      'loaded_guide': 'फोटो लोड हो गया • रेटिना का दायरा जांचें',
      'clinical_samples_title': 'क्लिनिकल परीक्षण नमूने (SIH 2026 मानक)',
      'confirm_quality': 'पुष्टि करें और गुणवत्ता जांचें',
      'reset': 'रीसेट करें',
      'optical_checklist_title': 'कैमरा फोटो गुणवत्ता जांच:',
      'chk_clarity': 'स्पष्टता: ठीक',
      'chk_light': 'रोशनी: पर्याप्त',
      'chk_center': 'केंद्र: सही केंद्र',
      'speak_guidance': 'मरीज को बोलकर सुनाएं',

      // Quality
      'quality_title': 'ऑप्टिकल गुणवत्ता सुरक्षा गेट',
      'sharpness': 'फोकस और स्पष्टता',
      'illumination': 'प्रकाश और रोशनी',
      'fov': 'दृष्टि क्षेत्र का कवरेज',
      'quality_good': 'उत्कृष्ट गुणवत्ता',
      'quality_borderline': 'मध्यम (CLAHE सुधार लागू)',
      'quality_ungradable': 'धुंधला चित्र — दोबारा फोटो आवश्यक',
      'proceed_inference': 'एआई विश्लेषण शुरू करें',
      'retake_image': 'दोबारा फोटो लें',

      // Results
      'ai_result_title': 'एआई निर्णय सहायता परिणाम',
      'level_0': 'कोई डायबिटिक रेटिनोपैथी नहीं (सामान्य)',
      'level_1': 'हल्की रेटिनोपैथी (Mild NPDR)',
      'level_2': 'मध्यम रेटिनोपैथी (Moderate NPDR)',
      'level_3': 'गंभीर रेटिनोपैथी (Severe NPDR)',
      'level_4': 'अत्यंत गंभीर रेटिनोपैथी (Proliferative DR)',
      'referable_yes': 'अस्पताल रेफरल आवश्यक',
      'referable_no': 'सामान्य — वार्षिक जांच पर्याप्त',
      'view_xai': 'व्याख्यात्मक हीटमैप देखें (Grad-CAM)',
      'view_report': 'परामर्श पर्ची व रिपोर्ट देखें',
      'new_screening': 'अगले मरीज की जांच करें',
      'patient_slip_btn': 'मरीज परामर्श पर्ची',

      // Explainability
      'xai_title': 'दृश्य व्याख्या (Grad-CAM हीटमैप)',
      'tab_original': 'मूल फोटो',
      'tab_gradcam': 'हीटमैप',
      'tab_overlay': 'संयुक्त दृश्य',
      'blend_opacity': 'हीटमैप पारदर्शिता:',
      'lesion_guide_title': 'रेटिना घाव एवं लक्षण मार्गदर्शिका',
      'attended_structures': 'एआई द्वारा पहचाने गए रेटिना क्षेत्र',

      // Report & Referral Slip
      'referral_card_title': 'मरीज परामर्श व रेफरल पर्ची',
      'slip_title': 'दृष्टि — टेली-रेटिना जांच एवं परामर्श पर्ची',
      'slip_subtitle': 'राष्ट्रीय अंधापन नियंत्रण कार्यक्रम (NPCB) सहयोग | SIH 2026',
      'slip_verified_title': 'जिला टेली-नेत्र रोग प्रमाणित',
      'slip_urgency_urgent': 'विशेषज्ञ डॉक्टर से तत्काल परामर्श आवश्यक',
      'slip_urgency_routine': 'दृष्टि सुरक्षित है • वार्षिक जांच पर्याप्त',
      'slip_advice_urgent': 'अस्पताल निर्देश: रोगी की आंख में मधुमेह के कारण नस संबंधी क्षति पाई गई है। कृपया अगले 7–14 दिनों के भीतर निकटतम जिला अस्पताल में नेत्र रोग विशेषज्ञ से मिलें।',
      'slip_advice_routine': 'परामर्श: आपकी रेटिना में फिलहाल कोई गंभीर क्षति नहीं है। हर वर्ष इसी तरह अपनी आंखों की जांच कराएं और ब्लड शुगर को नियंत्रित रखें।',
      'slip_tips_title': 'मरीज और परिवार हेतु मुख्य सावधानियां (Important Advice):',
      'slip_tip1_title': '1. शुगर नियंत्रण (HbA1c < 7%)',
      'slip_tip1_desc': 'खाली पेट और खाने के बाद ब्लड शुगर की नियमित जांच कराएं। तीन महीने वाली जांच 7% से नीचे रखें।',
      'slip_tip2_title': '2. नियमित दवा व बीपी नियंत्रण (< 130/80)',
      'slip_tip2_desc': 'उच्च रक्तचाप आंखों की बारीक नसों में सूजन और रक्तस्राव को बढ़ाता है। दवा समय पर लें।',
      'slip_tip3_title': '3. संतुलित व कम मीठा आहार',
      'slip_tip3_desc': 'हरी पत्तेदार सब्जियां, कम तेल और पर्याप्त पानी पिएं। चीनी और तली चीजें टालें।',
      'slip_tip4_title': '4. नियमित रेटिना जांच',
      'slip_tip4_desc': 'डायबिटिक रेटिनोपैथी शुरुआती दिनों में कोई दर्द नहीं देती। नियमित जांच ही बचाव है।',
      'slip_footer_doc': 'सत्यापित टेली-नेत्र विशेषज्ञ: डॉ. राजेश कुमार, MD (नेत्र रोग)',
      'slip_footer_notice': '*यह कम्प्यूटरीकृत टेली-स्क्रीनिंग पर्ची है, किसी भौतिक हस्ताक्षर की आवश्यकता नहीं है।',
      'slip_qr_label': 'QR सत्यापन',
      'slip_print_btn': 'पर्ची प्रिंट करें',
      'slip_share_btn': 'व्हाट्सएप पर भेजें',
      'urgency_immediate': 'जरूरी: 7–14 दिनों के भीतर नेत्र विशेषज्ञ से मिलें',
      'urgency_routine': 'नियमित: 12 महीने बाद वार्षिक जांच कराएं',
      'advice_hba1c': 'एचबीए1सी (HbA1c) 7% से नीचे बनाए रखें',
      'advice_bp': 'रक्तचाप नियंत्रित रखें (130/80 mmHg से कम)',
      'advice_diet': 'कम मीठा व संतुलित आहार लें',
      'print_pdf': 'परामर्श पर्ची (PDF) डाउनलोड करें',
      'share_slip': 'व्हाट्सएप पर भेजें',
    },

    'mr': {
      'app_title': 'दृष्टी (Drishti)',
      'tagline': 'ग्रामीण भारतासाठी स्पष्टीकरणात्मक एआय रेटिना तपासणी',
      'phc_screener': 'आरोग्य सेवक (PHC)',
      'specialist': 'नेत्ररोग तज्ज्ञ',
      'switch_to_doctor': 'डॉक्टर पोर्टल',
      'switch_to_screener': 'आरोग्य सेवक पोर्टल',
      'audio_guide': 'ऑडिओ मार्गदर्शक',
      'audio_on': 'व्हॉईस गाईड सुरू',
      'audio_off': 'व्हॉईस गाईड बंद',

      // 3-Step Guided Flow Ribbon
      'step1_ribbon': '1. रुग्णाची माहिती नोंदवा',
      'step2_ribbon': '2. रेटिना फोटो काढा',
      'step3_ribbon': '3. निकाल आणि संदर्भ स्लिप',

      'nav_dashboard': 'डॅशबोर्ड',
      'nav_intake': 'नवीन तपासणी',
      'nav_patients': 'रुग्ण यादी',
      'nav_sync': 'ग्रामीण सिंक',
      'nav_profile': 'प्रोफाइल',
      'nav_queue': 'समीक्षा रांग',
      'nav_cases': 'सर्व प्रकरणे',
      'nav_overview': 'सिंहावलोकन',
      'nav_reports': 'अहवाल',
      'greeting_morning': 'शुभ प्रभात',
      'greeting_afternoon': 'शुभ दुपार',
      'greeting_evening': 'शुभ संध्याकाळ',
      'stat_screened': 'एकूण तपासणी',
      'stat_screened_sub': 'नोंदणीकृत रुग्ण',
      'stat_referable': 'रेफरल आवश्यक',
      'stat_referable_sub': 'तज्ज्ञांसाठी ध्वजांकित',
      'stat_pending': 'प्रलंबित पुनरावलोकन',
      'stat_pending_sub': 'तज्ज्ञ रांगेत',
      'stat_completed': 'पूर्ण झाले',
      'stat_completed_sub': 'निदान पुष्टी',
      'start_screening': '+ नवीन तपासणी सुरू करा',
      'view_records': 'रुग्ण रेकॉर्ड पहा',
      'recent_screenings': 'अलीकडील तपासण्या',
      'view_all': 'सर्व पहा',
      'quick_demo_test': '⚡ क्लिनिकल चाचणी नमुने',
      'quick_demo_desc': 'कॅमेऱ्याशिवाय कोणत्याही टप्प्याची त्वरित चाचणी करा',
      'patient_demographics': 'रुग्ण माहिती',
      'patient_id': 'रुग्ण आयडी / टोकन',
      'age': 'वय (वर्षे)',
      'gender': 'लिंग',
      'gender_female': 'महिला',
      'gender_male': 'पुरुष',
      'gender_other': 'इतर',
      'diabetes_duration': 'मधुमेहाचा कालावधी (वर्षे)',
      'eye_selection': 'तपासणीसाठी डोळा निवडा',
      'right_eye': 'उजवा डोळा (OD)',
      'left_eye': 'डावा डोळा (OS)',
      'od_subtitle': 'उजवा डोळा • Oculus Dexter',
      'os_subtitle': 'डावा डोळा • Oculus Sinister',
      'proceed_capture': 'रेटिना फोटो घेण्यासाठी पुढे जा',
      'fill_demo': '⚡ डेमो रुग्ण भरा',
      'retinal_acquisition': 'रेटिनल फोटो संपादन',
      'camera_capture': 'कॅमेऱ्याने फोटो घ्या',
      'gallery_select': 'फाइल निवडा',
      'reticle_guide': 'ऑप्टिक डिस्क आणि मॅक्युला मध्यभागी ठेवा',
      'loaded_guide': 'फोटो लोड झाला • रेटिना क्षेत्र तपासा',
      'clinical_samples_title': 'क्लिनिकल चाचणी नमुने (SIH 2026 मानक)',
      'confirm_quality': 'गुणवत्ता तपासा',
      'reset': 'रीसेट करा',
      'optical_checklist_title': 'कॅमेरा फोटो गुणवत्ता तपासणी:',
      'chk_clarity': 'स्पष्टता: योग्य',
      'chk_light': 'प्रकाश: पुरेसा',
      'chk_center': 'केंद्र: योग्य केंद्र',
      'speak_guidance': 'रुग्णाला आवाजात ऐकवा',
      'quality_title': 'ऑप्टिकल गुणवत्ता सुरक्षा गेट',
      'sharpness': 'फोकस आणि स्पष्टता',
      'illumination': 'प्रकाश आणि एक्सपोजर',
      'fov': 'दृष्टी क्षेत्राचे कव्हरेज',
      'quality_good': 'उत्कृष्ट गुणवत्ता',
      'quality_borderline': 'मध्यम (CLAHE सुधारणा लागू)',
      'quality_ungradable': 'धूसर चित्र — पुन्हा फोटो आवश्यक',
      'proceed_inference': 'एआय विश्लेषण सुरू करा',
      'retake_image': 'पुन्हा फोटो घ्या',
      'ai_result_title': 'एआय निर्णय समर्थन निकाल',
      'level_0': 'रेटिनोपॅथी नाही (सामान्य)',
      'level_1': 'सौम्य रेटिनोपॅथी (Mild NPDR)',
      'level_2': 'मध्यम रेटिनोपॅथी (Moderate NPDR)',
      'level_3': 'गंभीर रेटिनोपॅथी (Severe NPDR)',
      'level_4': 'अत्यंत गंभीर रेटिनोपॅथी (Proliferative DR)',
      'referable_yes': 'विशेषज्ञ सल्ला आवश्यक',
      'referable_no': 'वार्षिक तपासणी पुरेशी',
      'view_xai': 'स्पष्टीकरणात्मक हीटमॅप पहा (Grad-CAM)',
      'view_report': 'संदर्भ स्लिप व अहवाल पहा',
      'new_screening': 'पुढील रुग्णाची तपासणी करा',
      'patient_slip_btn': 'रुग्ण संदर्भ स्लिप',
      'xai_title': 'व्हिज्युअल स्पष्टीकरण (Grad-CAM)',
      'tab_original': 'मूळ फोटो',
      'tab_gradcam': 'हीटमॅप',
      'tab_overlay': 'साक्ष्य आच्छादन',
      'blend_opacity': 'हीटमॅप पारदर्शकता:',
      'lesion_guide_title': 'रेटिना जखमा आणि बायोमार्कर मार्गदर्शक',
      'attended_structures': 'एआय द्वारे ओळखले गेलेले क्षेत्र',
      'referral_card_title': 'रुग्ण संदर्भ व सल्ला कार्ड',
      'slip_title': 'दृष्टी — टेलि-रेटिना तपासणी व संदर्भ चिठ्ठी',
      'slip_subtitle': 'राष्ट्रीय अंधत्व नियंत्रण कार्यक्रम (NPCB) सहयोग | SIH 2026',
      'slip_verified_title': 'जिल्हा टेलि-नेत्ररोग प्रमाणित',
      'slip_urgency_urgent': 'विशेषज्ञ डॉक्टरांचा तातडीचा सल्ला आवश्यक',
      'slip_urgency_routine': 'दृष्टी सुरक्षित आहे • वार्षिक तपासणी पुरेशी',
      'slip_advice_urgent': 'रुग्णालय सूचना: डोळ्यांत मधुमेहामुळे रक्तवाहिन्यांचे नुकसान दिसून आले आहे. कृपया 7–14 दिवसांत जिल्हा रुग्णालयात तज्ज्ञांना दाखवा.',
      'slip_advice_routine': 'सल्ला: सध्या डोळ्यात गंभीर दोष नाही. दरवर्षी नियमित तपासणी करा आणि रक्तातील साखर नियंत्रणात ठेवा.',
      'slip_tips_title': 'रुग्ण आणि कुटुंबासाठी महत्त्वाची खबरदारी:',
      'slip_tip1_title': '1. रक्तातील साखर नियंत्रण (HbA1c < 7%)',
      'slip_tip1_desc': 'औषधे वेळेवर घ्या. तीन महिन्यांची साखर तपासणी 7% खाली ठेवा.',
      'slip_tip2_title': '2. रक्तदाब नियंत्रित ठेवा (< 130/80)',
      'slip_tip2_desc': 'उच्च रक्तदाब डोळ्यांतील सूक्ष्म रक्तवाहिन्यांचे नुकसान करतो.',
      'slip_tip3_title': '3. कमी गोड व संतुलित आहार',
      'slip_tip3_desc': 'पालेभाज्या, कमी तेल आणि भरपूर पाणी प्या. गोड पदार्थ टाळा.',
      'slip_tip4_title': '4. नियमित डोळ्यांची तपासणी',
      'slip_tip4_desc': 'सुरुवातीला काहीही त्रास जाणवत नाही. नियमित तपासणीच दृष्टी वाचवू शकते.',
      'slip_footer_doc': 'प्रमाणित टेलि-नेत्रतज्ज्ञ: डॉ. राजेश कुमार, MD (नेत्ररोग)',
      'slip_footer_notice': '*ही संगणकीय टेलि-स्क्रीनिंग स्लिप आहे, कोणत्याही स्वाक्षरीची आवश्यकता नाही.',
      'slip_qr_label': 'QR पडताळणी',
      'slip_print_btn': 'स्लिप प्रिंट करा',
      'slip_share_btn': 'व्हॉट्सअॅपवर पाठवा',
      'urgency_immediate': 'तातडीने: 7–14 दिवसांत नेत्ररोग तज्ज्ञांना भेटा',
      'urgency_routine': 'नियमित: 12 महिन्यांनी वार्षिक तपासणी करा',
      'advice_hba1c': 'HbA1c 7% पेक्षा कमी ठेवा',
      'advice_bp': 'रक्तदाब नियंत्रित ठेवा (< 130/80)',
      'advice_diet': 'कमी साखरेचा संतुलित आहार घ्या',
      'print_pdf': 'स्लिप डाउनलोड करा (PDF)',
      'share_slip': 'व्हॉट्सअॅपवर शेअर करा',
    },

    'gu': {
      'app_title': 'દ્રષ્ટિ (Drishti)',
      'tagline': 'ગ્રામીણ ભારત માટે ડાયાબિટીક રેટિનોપેથી સ્ક્રીનિંગ',
      'phc_screener': 'આરોગ્ય કાર્યકર (PHC)',
      'specialist': 'આંખના નિષ્ણાત ડૉક્ટર',
      'switch_to_doctor': 'ડૉક્ટર પોર્ટલ',
      'switch_to_screener': 'આરોગ્ય કાર્યકર પોર્ટલ',
      'audio_guide': 'ઑડિયો સહાય',
      'audio_on': 'અવાજ માર્ગદર્શન ચાલુ',
      'audio_off': 'અવાજ માર્ગદર્શન બંધ',

      // 3-Step Guided Flow Ribbon
      'step1_ribbon': '1. દર્દીની વિગતો (Intake)',
      'step2_ribbon': '2. રેટિના ફોટો લો (Photo)',
      'step3_ribbon': '3. પરિણામ અને સ્લિપ (Result & Slip)',

      'nav_dashboard': 'ડેશબોર્ડ',
      'nav_intake': 'નવી તપાસ',
      'nav_patients': 'દર્દીઓની યાદી',
      'nav_sync': 'ગ્રામીણ સિંક',
      'nav_profile': 'પ્રોફાઇલ',
      'nav_queue': 'સમીક્ષા કતાર',
      'nav_cases': 'બધા કેસ',
      'nav_overview': 'ઝાંખી',
      'nav_reports': 'અહેવાલો',
      'greeting_morning': 'સુપ્રભાત',
      'greeting_afternoon': 'શુભ બપોર',
      'greeting_evening': 'શુભ સાંજ',
      'stat_screened': 'કુલ તપાસણી',
      'stat_screened_sub': 'નોંધાયેલા દર્દીઓ',
      'stat_referable': 'રેફરલ જરૂરી',
      'stat_referable_sub': 'ડૉક્ટર માટે ચિહ્નિત',
      'stat_pending': 'બાકી સમીક્ષા',
      'stat_pending_sub': 'નિષ્ણાત કતારમાં',
      'stat_completed': 'પૂર્ણ થયેલ',
      'stat_completed_sub': 'નિદાન પુષ્ટિ',
      'start_screening': '+ નવી તપાસ શરૂ કરો',
      'view_records': 'દર્દી રેકોર્ડ જુઓ',
      'recent_screenings': 'તાજેતરની તપાસણીઓ',
      'view_all': 'બધા જુઓ',
      'quick_demo_test': '⚡ ક્લિનિકલ ટેસ્ટ સેમ્પલ',
      'quick_demo_desc': 'કેમેરા વગર કોઈપણ તબક્કાની તાત્કાલિક તપાસ કરો',
      'patient_demographics': 'દર્દીની વિગતો',
      'patient_id': 'દર્દી ID / ટોકન',
      'age': 'ઉંમર (વર્ષ)',
      'gender': 'જાતિ',
      'gender_female': 'સ્ત્રી',
      'gender_male': 'પુરુષ',
      'gender_other': 'અન્ય',
      'diabetes_duration': 'ડાયાબિટીસનો સમયગાળો (વર્ષ)',
      'eye_selection': 'તપાસ માટે આંખ પસંદ કરો',
      'right_eye': 'જમણી આંખ (OD)',
      'left_eye': 'ડાબી આંખ (OS)',
      'od_subtitle': 'જમણી આંખ • Oculus Dexter',
      'os_subtitle': 'ડાબી આંખ • Oculus Sinister',
      'proceed_capture': 'રેટિના ફોટો લેવા આગળ વધો',
      'fill_demo': '⚡ ડેમો દર્દી ભરો',
      'retinal_acquisition': 'રેટિના ફોટો સંપાદન',
      'camera_capture': 'કેમેરાથી ફોટો લો',
      'gallery_select': 'ફાઇલમાંથી પસંદ કરો',
      'reticle_guide': 'ઑપ્ટિક ડિસ્ક અને મેક્યુલાને કેન્દ્રમાં રાખો',
      'loaded_guide': 'ફોટો લોડ થયો • રેટિના વિસ્તાર તપાસો',
      'clinical_samples_title': 'ક્લિનિકલ ટેસ્ટ સેમ્પલ (SIH 2026 ધોરણ)',
      'confirm_quality': 'ગુણવત્તા તપાસો',
      'reset': 'રીસેટ કરો',
      'optical_checklist_title': 'કેમેરા ફોટો ગુણવત્તા ચકાસણી:',
      'chk_clarity': 'સ્પષ્ટતા: બરાબર',
      'chk_light': 'પ્રકાશ: પૂરતો',
      'chk_center': 'કેન્દ્ર: બરાબર',
      'speak_guidance': 'દર્દીને બોલીને સંભળાવો',
      'quality_title': 'ઓપ્ટિકલ ગુણવત્તા સુરક્ષા ગેટ',
      'sharpness': 'ફોકસ અને સ્પષ્ટતા',
      'illumination': 'પ્રકાશ અને એક્સપોઝર',
      'fov': 'કવરેજ વિસ્તાર',
      'quality_good': 'શ્રેષ્ઠ ગુણવત્તા',
      'quality_borderline': 'મધ્યમ (CLAHE સુધારો લાગુ)',
      'quality_ungradable': 'ઝાંખો ફોટો — ફરીથી ફોટો જરૂરી',
      'proceed_inference': 'એઆઈ વિશ્લેષણ શરૂ કરો',
      'retake_image': 'ફરીથી ફોટો લો',
      'ai_result_title': 'એઆઈ નિર્ણય સહાય પરિણામ',
      'level_0': 'સામાન્ય (કોઈ રેટિનોપેથી નથી)',
      'level_1': 'હળવી રેટિનોપેથી (Mild NPDR)',
      'level_2': 'મધ્યમ રેટિનોપેથી (Moderate NPDR)',
      'level_3': 'ગંભીર રેટિનોપેથી (Severe NPDR)',
      'level_4': 'અત્યંત ગંભીર રેટિનોપેથી (PDR)',
      'referable_yes': 'ડૉક્ટર રેફરલ જરૂરી',
      'referable_no': 'સામાન્ય — વાર્ષિક તપાસ જરૂરી',
      'view_xai': 'હીટમેપ જુઓ (Grad-CAM)',
      'view_report': 'સ્લિપ અને રિપોર્ટ જુઓ',
      'new_screening': 'આગામી દર્દીની તપાસ કરો',
      'patient_slip_btn': 'દર્દી રેફરલ સ્લિપ',
      'xai_title': 'દ્રશ્ય સમજૂતી (Grad-CAM હીટમેપ)',
      'tab_original': 'મૂળ ફોટો',
      'tab_gradcam': 'હીટમેપ',
      'tab_overlay': 'પુરાવા ઓવરલે',
      'blend_opacity': 'હીટમેપ પારદર્શિતા:',
      'lesion_guide_title': 'રેટિના નુકસાન અને લક્ષણો માર્ગદર્શિકા',
      'attended_structures': 'એઆઈ દ્વારા ઓળખાયેલ વિસ્તારો',
      'referral_card_title': 'દર્દી રેફરલ અને સલાહ કાર્ડ',
      'slip_title': 'દ્રષ્ટિ — ટેલી-રેટિના તપાસ અને રેફરલ સ્લિપ',
      'slip_subtitle': 'રાષ્ટ્રીય અંધત્વ નિયંત્રણ કાર્યક્રમ (NPCB) સહયોગ | SIH 2026',
      'slip_verified_title': 'જિલ્લા ટેલિ-નેત્રરોગ પ્રમાણિત',
      'slip_urgency_urgent': 'નિષ્ણાત ડૉક્ટરની તાત્કાલિક સલાહ જરૂરી',
      'slip_urgency_routine': 'દ્રષ્ટિ સુરક્ષિત છે • વાર્ષિક તપાસ પૂરતી',
      'slip_advice_urgent': 'હોસ્પિટલ સૂચના: આંખમાં ડાયાબિટીસને કારણે નુકસાન જોવા મળ્યું છે. કૃપા કરીને 7–14 દિવસમાં જિલ્લા હોસ્પિટલમાં ડૉક્ટરને બતાવો.',
      'slip_advice_routine': 'સલાહ: હાલમાં કોઈ ગંભીર ખામી નથી. દર વર્ષે તપાસ કરાવો અને બ્લડ શુગર નિયંત્રણમાં રાખો.',
      'slip_tips_title': 'દર્દી અને પરિવાર માટે મહત્વપૂર્ણ સલાહ:',
      'slip_tip1_title': '1. શુગર નિયંત્રણ (HbA1c < 7%)',
      'slip_tip1_desc': 'દવા સમયસર લો. ત્રણ મહિનાની સુગર તપાસ 7% થી નીચે રાખો.',
      'slip_tip2_title': '2. બ્લડ પ્રેશર નિયંત્રણ (< 130/80)',
      'slip_tip2_desc': 'હાઈ બ્લડ પ્રેશર આંખની નાજુક નસોને નુકસાન પહોંચાડે છે.',
      'slip_tip3_title': '3. ઓછી ખાંડવાળો સંતુલિત ખોરાક',
      'slip_tip3_desc': 'લીલા શાકભાજી, ઓછું તેલ અને પૂરતું પાણી પીવો. ખાંડ ટાળો.',
      'slip_tip4_title': '4. નિયમિત રેટિના તપાસ',
      'slip_tip4_desc': 'શરૂઆતમાં કોઈ લક્ષણો દેખાતા નથી. નિયમિત તપાસથી જ આંખો સુરક્ષિત રહે છે.',
      'slip_footer_doc': 'પ્રમાણિત ટેલી-આંખના નિષ્ણાત: ડૉ. રાજેશ કુમાર, MD (ઓપ્થેલ્મોલોજી)',
      'slip_footer_notice': '*આ કમ્પ્યુટરાઇઝ્ડ ટેલી-સ્ક્રિનિંગ સ્લિપ છે, કોઈ ભૌતિક સહીની જરૂર નથી.',
      'slip_qr_label': 'QR ચકાસણી',
      'slip_print_btn': 'સ્લિપ પ્રિન્ટ કરો',
      'slip_share_btn': 'વોટ્સએપ પર મોકલો',
      'urgency_immediate': 'તાત્કાલિક: 7–14 દિવસમાં આંખના ડૉક્ટરને મળો',
      'urgency_routine': 'નિયમિત: 12 મહિના પછી વાર્ષિક તપાસ કરાવો',
      'advice_hba1c': 'HbA1c 7.0% થી નીચે રાખો',
      'advice_bp': 'બ્લડ પ્રેશર નિયંત્રણમાં રાખો (< 130/80)',
      'advice_diet': 'ઓછી ખાંડવાળો સંતુલિત ખોરાક લો',
      'print_pdf': 'પીડીએફ સ્લિપ ડાઉનલોડ કરો',
      'share_slip': 'વોટ્સએપ પર મોકલો',
    },

    'ta': {
      'app_title': 'திருஷ்டி (Drishti)',
      'tagline': 'கிராமப்புற இந்தியாவிற்கான விழித்திரை பரிசோதனை AI',
      'phc_screener': 'சுகாதார பணியாளர் (PHC)',
      'specialist': 'கண் மருத்துவர்',
      'switch_to_doctor': 'மருத்துவர் பக்கம்',
      'switch_to_screener': 'பணியாளர் பக்கம்',
      'audio_guide': 'ஒலி வழிகாட்டி',
      'audio_on': 'குரல் உதவி ஆன்',
      'audio_off': 'குரல் உதவி ஆஃப்',

      // 3-Step Guided Flow Ribbon
      'step1_ribbon': '1. நோயாளி விவரங்கள் (Intake)',
      'step2_ribbon': '2. விழித்திரை படம் எடு (Photo)',
      'step3_ribbon': '3. முடிவு & பரிந்துரை சீட்டு (Result & Slip)',

      'nav_dashboard': 'முகப்பு',
      'nav_intake': 'புதிய நோயாளி',
      'nav_patients': 'பட்டியல்',
      'nav_sync': 'ஒத்திசைவு',
      'nav_profile': 'சுயவிவரம்',
      'nav_queue': 'வரிசை',
      'nav_cases': 'அனைத்து வழக்குகள்',
      'nav_overview': 'மேற்பார்வை',
      'nav_reports': 'அறிக்கைகள்',
      'greeting_morning': 'காலை வணக்கம்',
      'greeting_afternoon': 'மதிய வணக்கம்',
      'greeting_evening': 'மாலை வணக்கம்',
      'stat_screened': 'பரிசோதிக்கப்பட்டவை',
      'stat_screened_sub': 'பதிவு செய்யப்பட்ட நோயாளிகள்',
      'stat_referable': 'பரிந்துரை தேவை',
      'stat_referable_sub': 'மருத்துவருக்கு பரிந்துரைக்கப்பட்டது',
      'stat_pending': 'மதிப்பாய்வு நிலுவை',
      'stat_pending_sub': 'வரிசையில் உள்ளது',
      'stat_completed': 'முடிந்தது',
      'stat_completed_sub': 'உறுதி செய்யப்பட்டது',
      'start_screening': '+ புதிய பரிசோதனை',
      'view_records': 'பதிவுகளைக் காண்க',
      'recent_screenings': 'சமீபத்திய பரிசோதனைகள்',
      'view_all': 'அனைத்தையும் காண்க',
      'quick_demo_test': '⚡ மாதிரி பரிசோதனை வழக்குகள்',
      'quick_demo_desc': 'கேமரா இல்லாமல் மாதிரி படங்களை உடனடியாக சோதிக்கவும்',
      'patient_demographics': 'நோயாளி விவரங்கள்',
      'patient_id': 'நோயாளி ID / டோக்கன்',
      'age': 'வயது (ஆண்டுகள்)',
      'gender': 'பாலினம்',
      'gender_female': 'பெண்',
      'gender_male': 'ஆண்',
      'gender_other': 'மற்றவை',
      'diabetes_duration': 'நீரிழிவு காலம் (ஆண்டுகள்)',
      'eye_selection': 'பரிசோதனைக்குரிய கண்',
      'right_eye': 'வலது கண் (OD)',
      'left_eye': 'இடது கண் (OS)',
      'od_subtitle': 'வலது கண் • Oculus Dexter',
      'os_subtitle': 'இடது கண் • Oculus Sinister',
      'proceed_capture': 'படம் எடுக்க தொடரவும்',
      'fill_demo': '⚡ மாதிரி நோயாளியை நிரப்பவும்',
      'retinal_acquisition': 'விழித்திரை படம் எடுத்தல்',
      'camera_capture': 'கேமரா மூலம் படம் எடு',
      'gallery_select': 'கோப்பிலிருந்து தேர்வு செய்',
      'reticle_guide': 'ஆப்டிக் டிஸ்க்கை மையத்தில் வைக்கவும்',
      'loaded_guide': 'படம் ஏற்றப்பட்டது • விழித்திரை பரப்பை சரிபார்க்கவும்',
      'clinical_samples_title': 'மாதிரி வழக்குகள் (SIH 2026 தரம்)',
      'confirm_quality': 'தரத்தை சரிபார்க்கவும்',
      'reset': 'மீட்டமைக்க',
      'optical_checklist_title': 'கேமரா படத் தர சரிபார்ப்பு:',
      'chk_clarity': 'தெளிவு: நன்று',
      'chk_light': 'வெளிச்சம்: போதுமானது',
      'chk_center': 'மையம்: நன்று',
      'speak_guidance': 'நோயாளிக்கு ஒலி வழிகாட்டல்',
      'quality_title': 'படத் தர பாதுகாப்பு வாயில்',
      'sharpness': 'தெளிவு மற்றும் கூர்மை',
      'illumination': 'வெளிச்சம் மற்றும் பிரகாசம்',
      'fov': 'கவரேஜ் பகுதி',
      'quality_good': 'சிறந்த தரம்',
      'quality_borderline': 'மிதமான தரம் (CLAHE மேம்படுத்தப்பட்டது)',
      'quality_ungradable': 'மங்கலான படம் — மீண்டும் படம் எடுக்கவும்',
      'proceed_inference': 'AI பகுப்பாய்வை தொடங்கவும்',
      'retake_image': 'மீண்டும் படம் எடுக்கவும்',
      'ai_result_title': 'AI முடிவு ஆதரவு மதிப்பீடு',
      'level_0': 'பாதிப்பில்லை (இயல்பு)',
      'level_1': 'லேசான பாதிப்பு (Mild NPDR)',
      'level_2': 'மிதமான பாதிப்பு (Moderate NPDR)',
      'level_3': 'கடுமையான பாதிப்பு (Severe NPDR)',
      'level_4': 'அதிதீவிர பாதிப்பு (PDR)',
      'referable_yes': 'மருத்துவமனை பரிந்துரை தேவை',
      'referable_no': 'ஆண்டு பரிசோதனை போதுமானது',
      'view_xai': 'ஹீட்மேப்பைக் காண்க (Grad-CAM)',
      'view_report': 'அறிக்கை மற்றும் சீட்டைப் பார்க்கவும்',
      'new_screening': 'அடுத்த நோயாளியை பரிசோதிக்கவும்',
      'patient_slip_btn': 'நோயாளி பரிந்துரை சீட்டு',
      'xai_title': 'காட்சி விளக்கம் (Grad-CAM ஹீட்மேப்)',
      'tab_original': 'அசல் படம்',
      'tab_gradcam': 'ஹீட்மேப்',
      'tab_overlay': 'மேலடுக்கு',
      'blend_opacity': 'ஹீட்மேப் ஒளிபுகாமை:',
      'lesion_guide_title': 'விழித்திரை பாதிப்பு வழிகாட்டி',
      'attended_structures': 'AI கவனித்த பகுதிகள்',
      'referral_card_title': 'நோயாளி பரிந்துரை அட்டை',
      'slip_title': 'திருஷ்டி — டெலி-விழித்திரை பரிசோதனை & பரிந்துரை சீட்டு',
      'slip_subtitle': 'தேசிய பார்வையிழப்பு தடுப்பு திட்டம் (NPCB) ஆதரவு | SIH 2026',
      'slip_verified_title': 'மாவட்ட கண் மருத்துவ சான்றளிக்கப்பட்டது',
      'slip_urgency_urgent': 'கண் மருத்துவரை உடனடியாக அணுகவும்',
      'slip_urgency_routine': 'பார்வைக்கு ஆபத்தில்லை • ஆண்டு பரிசோதனை போதுமானது',
      'slip_advice_urgent': 'மருத்துவமனை குறிப்பு: விழித்திரையில் பாதிப்பு கண்டறியப்பட்டுள்ளது. அடுத்த 7-14 நாட்களுக்குள் மாவட்ட கண் மருத்துவரை அணுகவும்.',
      'slip_advice_routine': 'ஆலோசனை: தற்போது தீவிர பாதிப்பு ஏதுமில்லை. இரத்த சர்க்கரையை கட்டுக்குள் வைத்து ஆண்டுதோறும் பரிசோதிக்கவும்.',
      'slip_tips_title': 'நோயாளி மற்றும் குடும்பத்திற்கான முக்கிய வழிகாட்டுதல்:',
      'slip_tip1_title': '1. இரத்த சர்க்கரை கட்டுப்பாடு (HbA1c < 7%)',
      'slip_tip1_desc': 'மருந்துகளை தவறாமல் உட்கொள்ளவும். HbA1c அளவை 7% க்குள் பராமரிக்கவும்.',
      'slip_tip2_title': '2. இரத்த அழுத்தம் கட்டுப்பாடு (< 130/80)',
      'slip_tip2_desc': 'உயர் இரத்த அழுத்தம் விழித்திரை இரத்த நாளங்களை பாதிக்கும்.',
      'slip_tip3_title': '3. சமச்சீர் சர்க்கரை குறைவான உணவு',
      'slip_tip3_desc': 'கீரை வகைகள், குறைந்த எண்ணெய், பழங்கள் மற்றும் போதிய தண்ணீர் அருந்தவும்.',
      'slip_tip4_title': '4. வழக்கமான விழித்திரை பரிசோதனை',
      'slip_tip4_desc': 'தொடக்கத்தில் வலி அல்லது அறிகுறி இருக்காது. வழக்கமான பரிசோதனையே பார்வை காக்கும்.',
      'slip_footer_doc': 'சரிபார்க்கப்பட்ட கண் மருத்துவர்: டாக்டர் ராஜேஷ் குமார், MD (கண் மருத்துவம்)',
      'slip_footer_notice': '*இது கணினி சரிபார்க்கப்பட்ட டெலி-ஸ்கிரீனிங் சீட்டு, கையொப்பம் தேவையில்லை.',
      'slip_qr_label': 'QR சரிபார்ப்பு',
      'slip_print_btn': 'சீட்டை அச்சிடுக',
      'slip_share_btn': 'வாட்ஸ்அப்பில் அனுப்பவும்',
      'urgency_immediate': 'அவசரம்: 7–14 நாட்களுக்குள் கண் மருத்துவரை அணுகவும்',
      'urgency_routine': 'வழக்கமானது: 12 மாதங்களில் ஆண்டு பரிசோதனை',
      'advice_hba1c': 'HbA1c 7.0% க்குள் பராமரிக்கவும்',
      'advice_bp': 'இரத்த அழுத்தத்தைக் கட்டுப்படுத்தவும் (< 130/80)',
      'advice_diet': 'சமச்சீர் சர்க்கரை குறைவான உணவு உண்ணவும்',
      'print_pdf': 'PDF சீட்டை பதிவிறக்கவும்',
      'share_slip': 'வாட்ஸ்அப்பில் பகிரவும்',
    },
  };

  static String tr(String key, String langCode) {
    final langMap = _localizedValues[langCode] ?? _localizedValues['en']!;
    return langMap[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
