class AppLanguage {
  final String code;
  final String name;
  final String localName;
  final String flag;

  const AppLanguage({
    required this.code,
    required this.name,
    required this.localName,
    required this.flag,
  });
}

class AppLocalizations {
  static const List<AppLanguage> supportedLanguages = [
    AppLanguage(code: 'en', name: 'English', localName: 'English', flag: '🇬🇧'),
    AppLanguage(code: 'hi', name: 'Hindi', localName: 'हिन्दी', flag: '🇮🇳'),
    AppLanguage(code: 'mr', name: 'Marathi', localName: 'मराठी', flag: '🇮🇳'),
    AppLanguage(code: 'gu', name: 'Gujarati', localName: 'ગુજરાતી', flag: '🇮🇳'),
    AppLanguage(code: 'ta', name: 'Tamil', localName: 'தமிழ்', flag: '🇮🇳'),
    AppLanguage(code: 'te', name: 'Telugu', localName: 'తెలుగు', flag: '🇮🇳'),
    AppLanguage(code: 'bn', name: 'Bengali', localName: 'বাংলা', flag: '🇮🇳'),
    AppLanguage(code: 'kn', name: 'Kannada', localName: 'ಕನ್ನಡ', flag: '🇮🇳'),
    AppLanguage(code: 'ml', name: 'Malayalam', localName: 'മലയാളം', flag: '🇮🇳'),
    AppLanguage(code: 'pa', name: 'Punjabi', localName: 'ਪੰਜਾਬੀ', flag: '🇮🇳'),
    AppLanguage(code: 'or', name: 'Odia', localName: 'ଓଡ଼ିଆ', flag: '🇮🇳'),
  ];

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Drishti',
      'tagline': 'Explainable AI Retinal Screening for Rural India',
      'phc_screener': 'PHC SCREENER',
      'specialist': 'OPHTHALMOLOGY SPECIALIST',
      'switch_to_doctor': 'Switch to Doctor',
      'switch_to_screener': 'Switch to Screener',
      'audio_guide': 'Audio Guide',
      'audio_on': 'Voice Guide On',
      'audio_off': 'Voice Guide Off',
      'select_language': 'Select Language / भाषा चुनें',
      'language_subtitle': 'Tailored for Primary Health Centers & frontline ASHA workers',
      'sign_out': 'Sign Out',
      'sign_out_title': 'Sign Out from Workstation?',
      'sign_out_desc': 'Your local offline session state will be safely preserved.',
      'cancel': 'Cancel',
      'cancel_session': 'Cancel Session',
      'token_active': 'TOKEN ACTIVE',
      'screener': 'Screener',
      'doctor': 'Doctor',
      'urgent_referrals': 'Urgent Referrals',
      'review_next_case': 'REVIEW NEXT CASE',
      'open_review_queue': 'Open Full Clinical Review Queue',
      'recent_cases': 'Recent Cases',
      'no_pending_cases': 'No pending cases awaiting diagnosis.',
      'risk_high': 'High Risk',
      'risk_low': 'Low Risk',
      'risk_moderate': 'Moderate',
      'risk_badge_high': 'High',
      'risk_badge_low': 'Low',
      'risk_badge_mod': 'Moderate',
      'patient_prefix': 'Patient',
      'level_prefix': 'Level',
      'no_screenings_today': 'No recent screenings recorded yet today.',
      'model_probability': 'MODEL PROBABILITY',
      'calibrated_confidence': 'CALIBRATED CONFIDENCE',
      'optical_quality': 'OPTICAL QUALITY',
      'softmax_probabilities': 'SOFTMAX CLASS PROBABILITIES',
      'triage_recommendation': 'AI CLINICAL TRIAGE RECOMMENDATION',
      'neural_classification': 'NEURAL RETINOPATHY CLASSIFICATION',
      'sample_prefix': 'Sample',
      'grading_in_progress': 'Grading in progress',
      'awaiting_ai_grading': 'Awaiting AI Grading',
      'auto_calibrated': 'Auto-Calibrated',
      'optimal': 'Optimal',
      'high_risk_flag': 'Flagged for Specialist',
      'specialist_validated': 'Specialist Validated',
      
      // 3-Step Guided Flow Ribbon
      'step1_ribbon': '1. Patient Intake & Context',
      'step2_ribbon': '2. Capture Retinal Image',
      'step3_ribbon': '3. Result & Referral Slip',
      'step1_short': 'Intake',
      'step2_short': 'Capture',
      'step3_short': 'Result',

      // Navigation
      'nav_dashboard': 'Dashboard',
      'nav_intake': 'New Intake',
      'nav_patients': 'Patients',
      'nav_sync': 'Rural Sync',
      'nav_profile': 'Profile',
      'nav_queue': 'Review Queue',
      'nav_cases': 'All Cases',
      'nav_overview': 'Overview',
      'nav_reports': 'Reports',

      // Dashboard
      'greeting_morning': 'Good morning',
      'greeting_afternoon': 'Good afternoon',
      'greeting_evening': 'Good evening',
      'stat_screened': 'Total Screened',
      'stat_screened_sub': 'Total patient intake',
      'stat_referable': 'AI Referable',
      'stat_referable_sub': 'Flagged for specialist',
      'stat_pending': 'Awaiting Review',
      'stat_pending_sub': 'In specialist queue',
      'stat_completed': 'Finalized',
      'stat_completed_sub': 'Diagnoses confirmed',
      'start_screening': 'START NEW SCREENING',
      'view_records': 'View Patient Records',
      'recent_screenings': 'Recent Screenings',
      'view_all': 'View All',
      'quick_demo_test': '⚡ Instant Clinical Test Samples',
      'quick_demo_desc': 'Test any DR stage instantly without physical camera',

      // Intake
      'patient_demographics': 'PATIENT DEMOGRAPHICS',
      'patient_id': 'Patient ID / Screening Token',
      'age': 'Age (Years)',
      'gender': 'Gender',
      'gender_female': 'Female',
      'gender_male': 'Male',
      'gender_other': 'Other',
      'diabetes_duration': 'Diabetes Duration (Years)',
      'eye_selection': 'EXAMINATION EYE',
      'right_eye': 'RIGHT EYE (OD)',
      'left_eye': 'LEFT EYE (OS)',
      'od_subtitle': 'Right Eye • Oculus Dexter',
      'os_subtitle': 'Left Eye • Oculus Sinister',
      'proceed_capture': 'Proceed to Retinal Capture',
      'fill_demo': '⚡ Fill Demo Patient',

      // Capture
      'retinal_acquisition': 'Retinal Fundus Image Acquisition',
      'camera_capture': 'Capture with Camera',
      'gallery_select': 'Select from File',
      'reticle_guide': 'Center optic disc & macula inside reticle guide',
      'loaded_guide': 'Retinal Image Loaded • Inspect Retinal FOV',
      'clinical_samples_title': 'CLINICAL TEST SAMPLES (SIH 2026 BENCHMARK)',
      'confirm_quality': 'Confirm & Evaluate Image Quality',
      'reset': 'Reset',
      'optical_checklist_title': 'Camera Photo Quality Check:',
      'chk_clarity': 'Focus & Sharpness: Clear',
      'chk_light': 'Lighting & Exposure: Adequate',
      'chk_center': 'Field of View: Centered',
      'speak_guidance': 'Speak Guidance to Patient',

      // Quality
      'quality_title': 'Optical Quality Safety Gate',
      'sharpness': 'Focus & Sharpness',
      'illumination': 'Illumination & Exposure',
      'fov': 'Field of View Coverage',
      'quality_good': 'GOOD QUALITY',
      'quality_borderline': 'BORDERLINE (ENHANCED)',
      'quality_ungradable': 'UNGRADABLE — RETAKE REQUIRED',
      'proceed_inference': 'Proceed to AI Diagnostic Inference',
      'retake_image': 'Recapture Retinal Photograph',

      // Results
      'ai_result_title': 'AI Decision Support Assessment',
      'level_0': 'No Diabetic Retinopathy',
      'level_1': 'Mild NPDR',
      'level_2': 'Moderate NPDR',
      'level_3': 'Severe NPDR',
      'level_4': 'Proliferative DR (Urgent)',
      'referable_yes': 'REFERRAL REQUIRED',
      'referable_no': 'NON-REFERABLE (ROUTINE)',
      'view_xai': 'View Explainable AI (Grad-CAM)',
      'view_report': 'View Clinical Report & Slip',
      'new_screening': 'Start Next Patient',
      'patient_slip_btn': 'Patient Referral Slip',

      // Explainability
      'xai_title': 'Visual Explainability (Grad-CAM)',
      'tab_original': 'ORIGINAL',
      'tab_gradcam': 'GRAD-CAM',
      'tab_overlay': 'OVERLAY',
      'blend_opacity': 'Overlay Blend:',
      'lesion_guide_title': 'RETINAL LESION & BIOMARKER GUIDE',
      'attended_structures': 'Model-Attended Retinal Zones',

      // Report & Referral Slip
      'referral_card_title': 'Patient Referral & Advice Card',
      'slip_title': 'DRISHTI — Tele-Retinal Screening & Referral Slip',
      'slip_subtitle': 'National Programme for Control of Blindness (NPCB) Support | SIH 2026',
      'slip_verified_title': 'DISTRICT TELE-OPHTHALMOLOGY VERIFIED',
      'slip_urgency_urgent': 'URGENT SPECIALIST REFERRAL REQUIRED',
      'slip_urgency_routine': 'NO SIGHT-THREATENING RETINOPATHY',
      'slip_advice_urgent': 'Hospital Instructions: Signs of diabetic vascular changes detected. Please consult an ophthalmologist at the district hospital within 7–14 days.',
      'slip_advice_routine': 'Clinical Advice: No immediate diabetic retinal lesions detected. Maintain strict blood sugar control and repeat annual screening in 12 months.',
      'slip_tips_title': 'Key Health Guidance for Patient and Family:',
      'slip_tip1_title': '1. Blood Sugar Control (HbA1c < 7.0%)',
      'slip_tip1_desc': 'Take medications/insulin on schedule. Maintain 3-month HbA1c below 7.0%.',
      'slip_tip2_title': '2. Blood Pressure Control (< 130/80 mmHg)',
      'slip_tip2_desc': 'Hypertension accelerates microvascular retinal leakage and hemorrhages.',
      'slip_tip3_title': '3. Balanced Diabetic Diet',
      'slip_tip3_desc': 'Eat green leafy vegetables, whole grains, and drink adequate water. Avoid refined sugars.',
      'slip_tip4_title': '4. Annual Retinal Examination',
      'slip_tip4_desc': 'Diabetic retinopathy causes no pain in early stages. Regular AI screening preserves sight.',
      'slip_footer_doc': 'Verified Tele-Ophthalmologist: Dr. Rajesh Kumar, MD (Ophthalmology)',
      'slip_footer_notice': '*This is a computer-verified tele-screening slip. No physical signature is required.',
      'slip_qr_label': 'QR Verify',
      'slip_print_btn': 'Print Referral Slip',
      'slip_share_btn': 'Share via WhatsApp',
      'urgency_immediate': 'URGENT: Consult Ophthalmologist within 7–14 days',
      'urgency_routine': 'ROUTINE: Annual Dilated Retinal Screening in 12 months',
      'advice_hba1c': 'Keep HbA1c below 7.0% with physician consultation',
      'advice_bp': 'Monitor blood pressure regularly (target < 130/80 mmHg)',
      'advice_diet': 'Follow balanced low-glycemic diabetic diet',
      'print_pdf': 'Download PDF Slip',
      'share_slip': 'Share via WhatsApp',
    },

    'hi': {
      'app_title': 'दृष्टि (Drishti)',
      'tagline': 'ग्रामीण भारत के लिए व्याख्यात्मक एआई रेटिना जांच',
      'phc_screener': 'प्राथमिक स्वास्थ्य कार्यकर्ता (PHC)',
      'specialist': 'नेत्र रोग विशेषज्ञ',
      'switch_to_doctor': 'डॉक्टर पोर्टल पर जाएं',
      'switch_to_screener': 'स्वास्थ्य कार्यकर्ता पोर्टल',
      'audio_guide': 'आवाज सहायता',
      'audio_on': 'ध्वनि मार्गदर्शन सक्रिय',
      'audio_off': 'ध्वनि मार्गदर्शन बंद',
      'select_language': 'भाषा चुनें / Select Language',
      'language_subtitle': 'प्राथमिक स्वास्थ्य केंद्रों व आशा कार्यकर्ताओं हेतु विशेष अनुकूलित',
      'sign_out': 'लॉग आउट',
      'sign_out_title': 'वर्कस्टेशन से लॉग आउट करें?',
      'sign_out_desc': 'आपका स्थानीय ऑफलाइन डेटा सुरक्षित रूप से सहेजा जाएगा।',
      'cancel': 'रद्द करें',
      'cancel_session': 'सत्र रद्द करें',
      'token_active': 'टोकन सक्रिय',
      'screener': 'जांचकर्ता',
      'doctor': 'डॉक्टर',
      'urgent_referrals': 'तत्काल रेफरल',
      'review_next_case': 'अगले मरीज की समीक्षा करें',
      'open_review_queue': 'पूर्ण समीक्षा कतार खोलें',
      'recent_cases': 'हाल के मामले',
      'no_pending_cases': 'निदान हेतु कोई लंबित मामला नहीं है।',
      'risk_high': 'उच्च जोखिम',
      'risk_low': 'कम जोखिम',
      'risk_moderate': 'मध्यम जोखिम',
      'risk_badge_high': 'उच्च',
      'risk_badge_low': 'कम',
      'risk_badge_mod': 'मध्यम',
      'patient_prefix': 'मरीज',
      'level_prefix': 'स्तर',
      'no_screenings_today': 'आज अभी तक कोई नई जांच दर्ज नहीं हुई है।',
      'model_probability': 'मॉडल सटीकता संभावना',
      'calibrated_confidence': 'कैलिब्रेटेड विश्वसनीयता',
      'optical_quality': 'ऑप्टिकल गुणवत्ता',
      'softmax_probabilities': 'सॉफ्टमैक्स वर्ग संभावनाएं',
      'triage_recommendation': 'एआई क्लिनिकल रेफरल अनुशंसा',
      'neural_classification': 'न्यूरल रेटिनोपैथी वर्गीकरण',
      'sample_prefix': 'नमूना',
      'grading_in_progress': 'जांच प्रक्रिया जारी है',
      'awaiting_ai_grading': 'एआई विश्लेषण की प्रतीक्षा है',
      'auto_calibrated': 'स्वतः-कैलिब्रेटेड',
      'optimal': 'सर्वोत्तम',
      'high_risk_flag': 'विशेषज्ञ के लिए चिह्नित',
      'specialist_validated': 'विशेषज्ञ द्वारा सत्यापित',

      // 3-Step Guided Flow Ribbon
      'step1_ribbon': '1. मरीज विवरण दर्ज करें (Intake)',
      'step2_ribbon': '2. रेटिना फोटो लें (Photo)',
      'step3_ribbon': '3. सरल परिणाम और पर्ची (Result & Slip)',
      'step1_short': 'विवरण',
      'step2_short': 'फोटो',
      'step3_short': 'परिणाम',

      // Navigation
      'nav_dashboard': 'डैशबोर्ड',
      'nav_intake': 'नई जांच',
      'nav_patients': 'मरीज सूची',
      'nav_sync': 'ग्रामीण सिंक',
      'nav_profile': 'प्रोफ़ाइल',
      'nav_queue': 'समीक्षा कतार',
      'nav_cases': 'सभी मामले',
      'nav_overview': 'सिंहावलोकन',
      'nav_reports': 'रिपोर्ट्स',

      // Dashboard
      'greeting_morning': 'शुभ प्रभात',
      'greeting_afternoon': 'शुभ दोपहर',
      'greeting_evening': 'शुभ संध्या',
      'stat_screened': 'कुल जांचे गए',
      'stat_screened_sub': 'पंजीकृत मरीज',
      'stat_referable': 'रेफरल योग्य',
      'stat_referable_sub': 'डॉक्टर के लिए चिह्नित',
      'stat_pending': 'समीक्षा लंबित',
      'stat_pending_sub': 'विशेषज्ञ कतार में',
      'stat_completed': 'सत्यापित',
      'stat_completed_sub': 'निदान पूर्ण हुआ',
      'start_screening': '+ नई रेटिना जांच शुरू करें',
      'view_records': 'मरीज रिकॉर्ड देखें',
      'recent_screenings': 'हाल की जांचें',
      'view_all': 'सभी देखें',
      'quick_demo_test': '⚡ त्वरित क्लिनिकल परीक्षण नमूने',
      'quick_demo_desc': 'बिना कैमरे के किसी भी चरण की तत्काल जांच करें',

      // Intake
      'patient_demographics': 'मरीज का विवरण',
      'patient_id': 'मरीज आईडी / टोकन नंबर',
      'age': 'आयु (वर्ष)',
      'gender': 'लिंग',
      'gender_female': 'महिला',
      'gender_male': 'पुरुष',
      'gender_other': 'अन्य',
      'diabetes_duration': 'मधुमेह की अवधि (वर्ष)',
      'eye_selection': 'जांच हेतु आंख चुनें',
      'right_eye': 'दाहिनी आंख (OD)',
      'left_eye': 'बायीं आंख (OS)',
      'od_subtitle': 'दाहिनी आंख • Oculus Dexter',
      'os_subtitle': 'बायीं आंख • Oculus Sinister',
      'proceed_capture': 'रेटिना फोटो लेने के लिए आगे बढ़ें',
      'fill_demo': '⚡ डेमो मरीज का विवरण भरें',

      // Capture
      'retinal_acquisition': 'रेटिनल फंडस फोटो अधिग्रहण',
      'camera_capture': 'कैमरे से फोटो लें',
      'gallery_select': 'गैलरी / फाइल से चुनें',
      'reticle_guide': 'ऑप्टिक डिस्क और मैकुला को केंद्र में रखें',
      'loaded_guide': 'फोटो लोड हो गया • रेटिना का दायरा जांचें',
      'clinical_samples_title': 'क्लिनिकल परीक्षण नमूने (SIH 2026 मानक)',
      'confirm_quality': 'पुष्टि करें और गुणवत्ता जांचें',
      'reset': 'रीसेट करें',
      'optical_checklist_title': 'कैमरा फोटो गुणवत्ता जांच:',
      'chk_clarity': 'स्पष्टता: ठीक',
      'chk_light': 'रोशनी: पर्याप्त',
      'chk_center': 'केंद्र: सही केंद्र',
      'speak_guidance': 'मरीज को बोलकर सुनाएं',

      // Quality
      'quality_title': 'ऑप्टिकल गुणवत्ता सुरक्षा गेट',
      'sharpness': 'फोकस और स्पष्टता',
      'illumination': 'प्रकाश और रोशनी',
      'fov': 'दृष्टि क्षेत्र का कवरेज',
      'quality_good': 'उत्कृष्ट गुणवत्ता',
      'quality_borderline': 'मध्यम (CLAHE सुधार लागू)',
      'quality_ungradable': 'धुंधला चित्र — दोबारा फोटो आवश्यक',
      'proceed_inference': 'एआई विश्लेषण शुरू करें',
      'retake_image': 'दोबारा फोटो लें',

      // Results
      'ai_result_title': 'एआई निर्णय सहायता परिणाम',
      'level_0': 'कोई डायबिटिक रेटिनोपैथी नहीं (सामान्य)',
      'level_1': 'हल्का डायबिटिक रेटिनोपैथी (Mild NPDR)',
      'level_2': 'मध्यम डायबिटिक रेटिनोपैथी (Moderate NPDR)',
      'level_3': 'गंभीर डायबिटिक रेटिनोपैथी (Severe NPDR)',
      'level_4': 'अति-गंभीर स्थिति (PDR - तत्काल रेफरल)',
      'referable_yes': 'अस्पताल रेफरल आवश्यक',
      'referable_no': 'नियमित वार्षिक जांच पर्याप्त',
      'view_xai': 'एआई हीटमैप देखें (Grad-CAM)',
      'view_report': 'विस्तृत रिपोर्ट व पर्ची देखें',
      'new_screening': 'अगले मरीज की जांच करें',
      'patient_slip_btn': 'मरीज रेफरल पर्ची',

      // Explainability
      'xai_title': 'दृश्य व्याख्या (Grad-CAM हीटमैप)',
      'tab_original': 'मूल फोटो',
      'tab_gradcam': 'हीटमैप',
      'tab_overlay': 'मिश्रित दृश्य',
      'blend_opacity': 'हीटमैप पारदर्शिता:',
      'lesion_guide_title': 'रेटिना घाव व बायोमार्कर गाइड',
      'attended_structures': 'एआई द्वारा चिन्हित रेटिना क्षेत्र',

      // Report & Referral Slip
      'referral_card_title': 'मरीज परामर्श एवं रेफरल कार्ड',
      'slip_title': 'दृष्टि — टेली-रेटिना जांच एवं रेफरल पर्ची',
      'slip_subtitle': 'राष्ट्रीय अंधापन नियंत्रण कार्यक्रम (NPCB) सहयोग | SIH 2026',
      'slip_verified_title': 'जिला टेली-नेत्र विज्ञान द्वारा सत्यापित',
      'slip_urgency_urgent': 'नेत्र रोग विशेषज्ञ से तत्काल परामर्श आवश्यक',
      'slip_urgency_routine': 'दृष्टि को कोई तात्कालिक खतरा नहीं • वार्षिक जांच आवश्यक',
      'slip_advice_urgent': 'अस्पताल निर्देश: रेटिना की रक्त वाहिकाओं में मधुमेह के लक्षण पाए गए हैं। कृपया 7-14 दिनों के भीतर जिला अस्पताल में नेत्र विशेषज्ञ से मिलें।',
      'slip_advice_routine': 'परामर्श: फिलहाल कोई गंभीर क्षति नहीं पाई गई। रक्त शर्करा को नियंत्रित रखें और 12 महीने बाद पुनः जांच कराएं।',
      'slip_tips_title': 'मरीज व परिवार के लिए आवश्यक स्वास्थ्य निर्देश:',
      'slip_tip1_title': '1. रक्त शर्करा नियंत्रण (HbA1c < 7.0%)',
      'slip_tip1_desc': 'दवाएं/इंसुलिन समय पर लें। 3 महीने की औसत शर्करा (HbA1c) 7% से कम रखें।',
      'slip_tip2_title': '2. रक्तचाप नियंत्रण (< 130/80 mmHg)',
      'slip_tip2_desc': 'उच्च रक्तचाप आंखों की सूक्ष्म नसों को नुकसान पहुंचाता है।',
      'slip_tip3_title': '3. संतुलित व कम मीठा आहार',
      'slip_tip3_desc': 'हरी सब्जियां, कम तेल-मसाला और पर्याप्त पानी लें। चीनी से बचें।',
      'slip_tip4_title': '4. नियमित वार्षिक रेटिना जांच',
      'slip_tip4_desc': 'शुरुआती दौर में कोई दर्द या लक्षण नहीं होते। नियमित जांच ही दृष्टि बचाती है।',
      'slip_footer_doc': 'प्रमाणित टेली-नेत्र विशेषज्ञ: डॉ. राजेश कुमार, MD (नेत्र रोग)',
      'slip_footer_notice': '*यह कम्प्यूटरीकृत टेली-स्क्रीनिंग पर्ची है, भौतिक हस्ताक्षर की आवश्यकता नहीं है।',
      'slip_qr_label': 'QR सत्यापन',
      'slip_print_btn': 'रेफरल पर्ची प्रिंट करें',
      'slip_share_btn': 'व्हाट्सएप पर भेजें',
      'urgency_immediate': 'तत्काल: 7–14 दिनों में नेत्र विशेषज्ञ से मिलें',
      'urgency_routine': 'नियमित: 12 महीने बाद वार्षिक जांच कराएं',
      'advice_hba1c': 'HbA1c 7.0% से नीचे रखें',
      'advice_bp': 'रक्तचाप नियंत्रित रखें (< 130/80)',
      'advice_diet': 'कम शर्करा युक्त संतुलित आहार लें',
      'print_pdf': 'पीडीएफ पर्ची डाउनलोड करें',
      'share_slip': 'व्हाट्सएप पर शेयर करें',
    },

    'mr': {
      'app_title': 'दृष्टी (Drishti)',
      'tagline': 'ग्रामीण भारतासाठी स्पष्टीकरणात्मक एआय डोळ्यांची तपासणी',
      'phc_screener': 'आरोग्य सेवक (PHC)',
      'specialist': 'नेत्रतज्ज्ञ',
      'switch_to_doctor': 'डॉक्टर पोर्टल',
      'switch_to_screener': 'आरोग्य सेवक पोर्टल',
      'audio_guide': 'आवाज सहाय्य',
      'audio_on': 'व्हॉईस गाईड चालू',
      'audio_off': 'व्हॉईस गाईड बंद',
      'select_language': 'भाषा निवडा / Select Language',
      'language_subtitle': 'प्राथमिक आरोग्य केंद्रे व आशा सेविकांसाठी विशेष रचना',
      'sign_out': 'बाहेर पडा (लॉग आउट)',
      'sign_out_title': 'वर्कस्टेशनवरून बाहेर पडायचे?',
      'sign_out_desc': 'तुमचा स्थानिक ऑफलाइन डेटा सुरक्षित साठवला जाईल.',
      'cancel': 'रद्द करा',
      'cancel_session': 'सत्र रद्द करा',
      'token_active': 'टोकन सक्रिय',
      'screener': 'तपासणीस',
      'doctor': 'डॉक्टर',
      'urgent_referrals': 'तातडीचे रेफरल',
      'review_next_case': 'पुढील रुग्णाची तपासणी करा',
      'open_review_queue': 'पूर्ण पुनरावलोकन यादी उघडा',
      'recent_cases': 'अलीकडील केसेस',
      'no_pending_cases': 'निदानासाठी कोणतीही प्रलंबित केस नाही.',
      'risk_high': 'उच्च धोका',
      'risk_low': 'कमी धोका',
      'risk_moderate': 'मध्यम धोका',
      'risk_badge_high': 'उच्च',
      'risk_badge_low': 'कमी',
      'risk_badge_mod': 'मध्यम',
      'patient_prefix': 'रुग्ण',
      'level_prefix': 'पातळी',
      'no_screenings_today': 'आज कोणतीही नवीन नोंदणी झालेली नाही.',
      'model_probability': 'मॉडेल अचूकता संभाव्यता',
      'calibrated_confidence': 'कॅलिब्रेटेड आत्मविश्वास',
      'optical_quality': 'ऑप्टिकल गुणवत्ता',
      'softmax_probabilities': 'सॉफ्टमॅक्स वर्ग संभाव्यता',
      'triage_recommendation': 'एआय क्लिनिकल रेफरल शिफारस',
      'neural_classification': 'न्यूरल रेटिनोपॅथी वर्गीकरण',
      'sample_prefix': 'नमुना',
      'grading_in_progress': 'तपासणी सुरू आहे',
      'awaiting_ai_grading': 'एआय विश्लेषणाची प्रतीक्षा आहे',
      'auto_calibrated': 'स्वयं-कॅलिब्रेटेड',
      'optimal': 'उत्कृष्ट',
      'high_risk_flag': 'तज्ज्ञांसाठी चिन्हांकित',
      'specialist_validated': 'तज्ज्ञांकडून प्रमाणित',

      // 3-Step Guided Flow Ribbon
      'step1_ribbon': '1. रुग्ण माहिती (Intake)',
      'step2_ribbon': '2. डोळ्याचा फोटो घ्या (Photo)',
      'step3_ribbon': '3. सोपे निकाल व स्लिप (Result & Slip)',
      'step1_short': 'माहिती',
      'step2_short': 'फोटो',
      'step3_short': 'निकाल',

      // Navigation
      'nav_dashboard': 'डॅशबोर्ड',
      'nav_intake': 'नवीन रुग्ण',
      'nav_patients': 'रुग्ण यादी',
      'nav_sync': 'ग्रामीण सिंक',
      'nav_profile': 'प्रोफाइल',
      'nav_queue': 'पुनरावलोकन रांग',
      'nav_cases': 'सर्व केसेस',
      'nav_overview': 'आढावा',
      'nav_reports': 'अहवाल',

      // Dashboard
      'greeting_morning': 'शुभ सकाळ',
      'greeting_afternoon': 'शुभ दुपार',
      'greeting_evening': 'शुभ संध्याकाळ',
      'stat_screened': 'एकूण तपासलेले',
      'stat_screened_sub': 'नोंदणीकृत रुग्ण',
      'stat_referable': 'रेफरल आवश्यक',
      'stat_referable_sub': 'डॉक्टरांकडे पाठवले',
      'stat_pending': 'पुनरावलोकन प्रलंबित',
      'stat_pending_sub': 'तज्ज्ञ रांगेत',
      'stat_completed': 'पूर्ण झाले',
      'stat_completed_sub': 'निदान निश्चित',
      'start_screening': '+ नवीन डोळ्यांची तपासणी सुरू करा',
      'view_records': 'रुग्ण नोंदी पहा',
      'recent_screenings': 'अलीकडील तपासण्या',
      'view_all': 'सर्व पहा',
      'quick_demo_test': '⚡ चाचणी नमुने (डेमो)',
      'quick_demo_desc': 'कॅमेऱ्याशिवाय नमुना फोटो तपासा',

      // Intake
      'patient_demographics': 'रुग्णाची माहिती',
      'patient_id': 'रुग्ण आयडी / टोकन नंबर',
      'age': 'वय (वर्षे)',
      'gender': 'लिंग',
      'gender_female': 'महिला',
      'gender_male': 'पुरुष',
      'gender_other': 'इतर',
      'diabetes_duration': 'मधुमेहाचा कालावधी (वर्षे)',
      'eye_selection': 'तपासणीचा डोळा निवडा',
      'right_eye': 'उजवा डोळा (OD)',
      'left_eye': 'डावा डोळा (OS)',
      'od_subtitle': 'उजवा डोळा • Oculus Dexter',
      'os_subtitle': 'डावा डोळा • Oculus Sinister',
      'proceed_capture': 'फोटो घेण्यासाठी पुढे जा',
      'fill_demo': '⚡ डेमो रुग्ण भरा',

      // Capture
      'retinal_acquisition': 'रेटिनल फोटो घेणे',
      'camera_capture': 'कॅमेऱ्याने फोटो घ्या',
      'gallery_select': 'फाइलमधून निवडा',
      'reticle_guide': 'ऑप्टिक डिस्क मध्यभागी ठेवा',
      'loaded_guide': 'फोटो लोड झाला • रेटिना तपासा',
      'clinical_samples_title': 'क्लिनिकल चाचणी नमुने (SIH 2026 मानक)',
      'confirm_quality': 'गुणवत्ता तपासा व निश्चित करा',
      'reset': 'रीसेट करा',
      'optical_checklist_title': 'कॅमेरा फोटो गुणवत्ता तपासणी:',
      'chk_clarity': 'स्पष्टता: उत्तम',
      'chk_light': 'प्रकाश: पुरेसा',
      'chk_center': 'केंद्र: योग्य',
      'speak_guidance': 'रुग्णाला मार्गदर्शन सांगा',

      // Quality
      'quality_title': 'फोटो गुणवत्ता तपासणी गेट',
      'sharpness': 'फोकस आणि स्पष्टता',
      'illumination': 'प्रकाश आणि ब्राइटनेस',
      'fov': 'दृष्टी क्षेत्र व्याप्ती',
      'quality_good': 'उत्कृष्ट गुणवत्ता',
      'quality_borderline': 'मध्यम गुणवत्ता (CLAHE सुधारणा)',
      'quality_ungradable': 'अस्पष्ट फोटो — कृपया पुन्हा फोटो घ्या',
      'proceed_inference': 'एआय तपासणी सुरू करा',
      'retake_image': 'पुन्हा फोटो घ्या',

      // Results
      'ai_result_title': 'एआय निर्णय सहाय्य निकाल',
      'level_0': 'कोणताही परिणाम नाही (सामान्य)',
      'level_1': 'सौम्य परिणाम (Mild NPDR)',
      'level_2': 'मध्यम परिणाम (Moderate NPDR)',
      'level_3': 'गंभीर परिणाम (Severe NPDR)',
      'level_4': 'अति-गंभीर स्थिती (तातडीचे रेफरल)',
      'referable_yes': 'रुग्णालयात रेफरल आवश्यक',
      'referable_no': 'वार्षिक तपासणी पुरेशी आहे',
      'view_xai': 'हीटमॅप पहा (Grad-CAM)',
      'view_report': 'सविस्तर अहवाल व स्लिप पहा',
      'new_screening': 'पुढील रुग्णाची तपासणी करा',
      'patient_slip_btn': 'रुग्ण रेफरल स्लिप',

      // Explainability
      'xai_title': 'व्हिज्युअल स्पष्टीकरण (Grad-CAM)',
      'tab_original': 'मूळ फोटो',
      'tab_gradcam': 'हीटमॅप',
      'tab_overlay': 'मिश्रित दृश्य',
      'blend_opacity': 'हीटमॅप पारदर्शकता:',
      'lesion_guide_title': 'रेटिना जखमा व लक्षणे मार्गदर्शक',
      'attended_structures': 'एआयने तपासलेले भाग',

      // Report & Referral Slip
      'referral_card_title': 'रुग्ण रेफरल व सल्ला कार्ड',
      'slip_title': 'दृष्टी — टेली-रेटिना तपासणी व रेफरल स्लिप',
      'slip_subtitle': 'राष्ट्रीय अंधत्व नियंत्रण कार्यक्रम (NPCB) सहाय्य | SIH 2026',
      'slip_verified_title': 'जिल्हा टेली-नेत्ररोग तज्ज्ञांकडून प्रमाणित',
      'slip_urgency_urgent': 'तातडीने नेत्ररोग तज्ज्ञांना भेटा',
      'slip_urgency_routine': 'दृष्टीला कोणताही धोका नाही • वार्षिक तपासणी आवश्यक',
      'slip_advice_urgent': 'रुग्णालय सूचना: डोळ्याच्या पडद्यावर मधुमेहाचे परिणाम आढळले आहेत. कृपया पुढील 7-14 दिवसांत जिल्हा रुग्णालयात नेत्रतज्ज्ञांना भेटा.',
      'slip_advice_routine': 'सल्ला: सध्या कोणताही गंभीर परिणाम नाही. रक्तातील साखर नियंत्रणात ठेवा व 12 महिन्यांनी पुन्हा तपासणी करा.',
      'slip_tips_title': 'रुग्ण आणि कुटुंबासाठी महत्त्वाची मार्गदर्शक तत्त्वे:',
      'slip_tip1_title': '1. रक्तातील साखर नियंत्रण (HbA1c < 7.0%)',
      'slip_tip1_desc': 'औषधे नियमित घ्या. तीन महिन्यांची सरासरी साखर 7% पेक्षा कमी ठेवा.',
      'slip_tip2_title': '2. रक्तदाब नियंत्रण (< 130/80 mmHg)',
      'slip_tip2_desc': 'उच्च रक्तदाबामुळे डोळ्यांच्या नाजूक रक्तवाहिन्यांना इजा होते.',
      'slip_tip3_title': '3. कमी साखरेचा संतुलित आहार',
      'slip_tip3_desc': 'हिरव्या पालेभाज्या, कमी तेल आणि भरपूर पाणी प्या. साखर टाळा.',
      'slip_tip4_title': '4. नियमित रेटिना तपासणी',
      'slip_tip4_desc': 'सुरुवातीला कोणतीही लक्षणे जाणवत नाहीत. नियमित तपासणीनेच दृष्टी वाचते.',
      'slip_footer_doc': 'प्रमाणित टेली-नेत्रतज्ज्ञ: डॉ. राजेश कुमार, MD (नेत्ररोग)',
      'slip_footer_notice': '*ही संगणकीकृत टेली-स्क्रीनिंग स्लिप आहे, कोणत्याही स्वाक्षरीची गरज नाही.',
      'slip_qr_label': 'QR पडताळणी',
      'slip_print_btn': 'स्लिप प्रिंट करा',
      'slip_share_btn': 'व्हॉट्सॲपवर पाठवा',
      'urgency_immediate': 'तातडीचे: 7–14 दिवसांत नेत्रतज्ज्ञांना भेटा',
      'urgency_routine': 'नियमित: 12 महिन्यांनी वार्षिक तपासणी',
      'advice_hba1c': 'HbA1c 7.0% पेक्षा कमी ठेवा',
      'advice_bp': 'रक्तदाब नियंत्रणात ठेवा (< 130/80)',
      'advice_diet': 'कमी साखरेचा संतुलित आहार घ्या',
      'print_pdf': 'पीडीएफ स्लिप डाउनलोड करा',
      'share_slip': 'व्हॉट्सॲपवर शेअर करा',
    },

    'gu': {
      'app_title': 'દ્રષ્ટિ (Drishti)',
      'tagline': 'ગ્રામીણ ભારત માટે AI આંખની રેટિના તપાસ',
      'phc_screener': 'આરોગ્ય કાર્યકર (PHC)',
      'specialist': 'આંખના નિષ્ણાત (ડૉક્ટર)',
      'switch_to_doctor': 'ડૉક્ટર પોર્ટલ',
      'switch_to_screener': 'આરોગ્ય કાર્યકર પોર્ટલ',
      'audio_guide': 'અવાજ માર્ગદર્શન',
      'audio_on': 'વોઈસ ગાઈડ ચાલુ',
      'audio_off': 'વોઈસ ગાઈડ બંધ',
      'select_language': 'ભાષા પસંદ કરો / Select Language',
      'language_subtitle': 'પ્રાથમિક આરોગ્ય કેન્દ્રો અને આશા કાર્યકરો માટે ખાસ અનુકૂળ',
      'sign_out': 'લૉગ આઉટ',
      'sign_out_title': 'વર્કસ્ટેશનમાંથી લૉગ આઉટ કરવું છે?',
      'sign_out_desc': 'તમારો સ્થાનિક ઑફલાઇન ડેટા સુરક્ષિત સંગ્રહિત રહેશે.',
      'cancel': 'રદ કરો',
      'cancel_session': 'સત્ર રદ કરો',
      'token_active': 'ટોકન સક્રિય',
      'screener': 'સ્ક્રીનર',
      'doctor': 'ડૉક્ટર',
      'urgent_referrals': 'તાત્કાલિક રેફરલ',
      'review_next_case': 'આગામી દર્દીની સમીક્ષા કરો',
      'open_review_queue': 'સંપૂર્ણ સમીક્ષા યાદી ખોલો',
      'recent_cases': 'તાજેતરના કેસો',
      'no_pending_cases': 'નિદાન માટે કોઈ બાકી કેસ નથી.',
      'risk_high': 'વધુ જોખમ',
      'risk_low': 'ઓછું જોખમ',
      'risk_moderate': 'મધ્યમ જોખમ',
      'risk_badge_high': 'ઉચ્ચ',
      'risk_badge_low': 'ઓછું',
      'risk_badge_mod': 'મધ્યમ',
      'patient_prefix': 'દર્દી',
      'level_prefix': 'સ્તર',
      'no_screenings_today': 'આજે હજુ સુધી કોઈ નવી તપાસ નોંધાઈ નથી.',
      'model_probability': 'મૉડલ ચોકસાઈ સંભાવના',
      'calibrated_confidence': 'કૅલિબ્રેટેડ આત્મવિશ્વાસ',
      'optical_quality': 'ઓપ્ટિકલ ગુણવત્તા',
      'softmax_probabilities': 'સોફ્ટમેક્સ વર્ગ સંભાવનાઓ',
      'triage_recommendation': 'AI ક્લિનિકલ રેફરલ ભલામણ',
      'neural_classification': 'ન્યુરલ રેટિનોપેથી વર્ગીકરણ',
      'sample_prefix': 'નમૂનો',
      'grading_in_progress': 'તપાસ ચાલુ છે',
      'awaiting_ai_grading': 'AI વિશ્લેષણની રાહ જોઈ રહ્યા છીએ',
      'auto_calibrated': 'સ્વતઃ-કૅલિબ્રેટેડ',
      'optimal': 'ઉત્તમ',
      'high_risk_flag': 'નિષ્ણાત માટે ચિહ્નિત',
      'specialist_validated': 'નિષ્ણાત દ્વારા પ્રમાણિત',

      // 3-Step Guided Flow Ribbon
      'step1_ribbon': '1. દર્દીની વિગતો (Intake)',
      'step2_ribbon': '2. રેટિનાનો ફોટો લો (Photo)',
      'step3_ribbon': '3. સરળ પરિણામ અને સ્લિપ (Result & Slip)',
      'step1_short': 'વિગતો',
      'step2_short': 'ફોટો',
      'step3_short': 'પરિણામ',

      // Navigation
      'nav_dashboard': 'ડેશબોર્ડ',
      'nav_intake': 'નવો દર્દી',
      'nav_patients': 'દર્દી યાદી',
      'nav_sync': 'ગ્રામીણ સિંક',
      'nav_profile': 'પ્રોફાઇલ',
      'nav_queue': 'સમીક્ષા કતાર',
      'nav_cases': 'બધા કેસો',
      'nav_overview': 'સમીક્ષા',
      'nav_reports': 'અહેવાલો',

      // Dashboard
      'greeting_morning': 'શુભ સવાર',
      'greeting_afternoon': 'શુભ બપોર',
      'greeting_evening': 'શુભ સાંજ',
      'stat_screened': 'કુલ તપાસેલ',
      'stat_screened_sub': 'નોંધાયેલ દર્દીઓ',
      'stat_referable': 'રેફરલ યોગ્ય',
      'stat_referable_sub': 'ડૉક્ટર પાસે મોકલેલ',
      'stat_pending': 'સમીક્ષા બાકી',
      'stat_pending_sub': 'કતારમાં છે',
      'stat_completed': 'પૂર્ણ થયેલ',
      'stat_completed_sub': 'નિદાન થયેલ',
      'start_screening': '+ નવી આંખ તપાસ શરૂ કરો',
      'view_records': 'દર્દી રેકોર્ડ જુઓ',
      'recent_screenings': 'તાજેતરની તપાસો',
      'view_all': 'બધા જુઓ',
      'quick_demo_test': '⚡ ક્લિનિકલ ટેસ્ટ નમૂનાઓ',
      'quick_demo_desc': 'કેમેરા વગર સીધો નમૂના ફોટો તપાસો',

      // Intake
      'patient_demographics': 'દર્દીની વિગતો',
      'patient_id': 'દર્દી ID / ટોકન નંબર',
      'age': 'ઉંમર (વર્ષ)',
      'gender': 'જાતિ',
      'gender_female': 'સ્ત્રી',
      'gender_male': 'પુરુષ',
      'gender_other': 'અન્ય',
      'diabetes_duration': 'ડાયાબિટીસનો સમયગાળો (વર્ષ)',
      'eye_selection': 'તપાસ માટે આંખ પસંદ કરો',
      'right_eye': 'જમણી આંખ (OD)',
      'left_eye': 'ડાબી આંખ (OS)',
      'od_subtitle': 'જમણી આંખ • Oculus Dexter',
      'os_subtitle': 'ડાબી આંખ • Oculus Sinister',
      'proceed_capture': 'ફોટો લેવા આગળ વધો',
      'fill_demo': '⚡ ડેમો દર્દી ભરો',

      // Capture
      'retinal_acquisition': 'રેટિના ફોટો મેળવો',
      'camera_capture': 'કેમેરાથી ફોટો લો',
      'gallery_select': 'ફાઇલમાંથી પસંદ કરો',
      'reticle_guide': 'ઓપ્ટિક ડિસ્કને કેન્દ્રમાં રાખો',
      'loaded_guide': 'ફોટો લોડ થયો • રેટિના વિસ્તાર તપાસો',
      'clinical_samples_title': 'ક્લિનિકલ ટેસ્ટ કેસ (SIH 2026 ધોરણ)',
      'confirm_quality': 'ગુણવત્તા તપાસો અને પુષ્ટિ કરો',
      'reset': 'રીસેટ',
      'optical_checklist_title': 'કેમેરા ફોટો ગુણવત્તા તપાસ:',
      'chk_clarity': 'સ્પષ્ટતા: સારી',
      'chk_light': 'પ્રકાશ: પૂરતો',
      'chk_center': 'કેન્દ્ર: યોગ્ય',
      'speak_guidance': 'દર્દીને અવાજ સંભળાવો',

      // Quality
      'quality_title': 'ફોટો ગુણવત્તા સુરક્ષા ગેટ',
      'sharpness': 'ફોકસ અને સ્પષ્ટતા',
      'illumination': 'પ્રકાશ અને બ્રાઇટનેસ',
      'fov': 'કવરેજ વિસ્તાર',
      'quality_good': 'ઉત્તમ ગુણવત્તા',
      'quality_borderline': 'મધ્યમ (CLAHE સુધારો લાગુ)',
      'quality_ungradable': 'અસ્પષ્ટ ફોટો — ફરીથી ફોટો લો',
      'proceed_inference': 'AI વિશ્લેષણ શરૂ કરો',
      'retake_image': 'ફરીથી ફોટો લો',

      // Results
      'ai_result_title': 'AI નિર્ણય સહાય પરિણામ',
      'level_0': 'સામાન્ય (કોઈ અસર નથી)',
      'level_1': 'હળવી અસર (Mild NPDR)',
      'level_2': 'મધ્યમ અસર (Moderate NPDR)',
      'level_3': 'ગંભીર અસર (Severe NPDR)',
      'level_4': 'અતિ-ગંભીર અસર (તાત્કાલિક રેફરલ)',
      'referable_yes': 'હોસ્પિટલ રેફરલ જરૂરી',
      'referable_no': 'વાર્ષિક તપાસ પૂરતી છે',
      'view_xai': 'હીટમેપ જુઓ (Grad-CAM)',
      'view_report': 'રિપોર્ટ અને સ્લિપ જુઓ',
      'new_screening': 'આગામી દર્દીની તપાસ કરો',
      'patient_slip_btn': 'દર્દી રેફરલ સ્લિપ',

      // Explainability
      'xai_title': 'વિઝ્યુઅલ સમજૂતી (Grad-CAM હીટમેપ)',
      'tab_original': 'મૂળ ફોટો',
      'tab_gradcam': 'હીટમેપ',
      'tab_overlay': 'ઓવરલે',
      'blend_opacity': 'હીટમેપ પારદર્શિતા:',
      'lesion_guide_title': 'રેટિના નુકસાન માર્ગદર્શિકા',
      'attended_structures': 'AI દ્વારા ધ્યાનમાં લીધેલ ભાગો',

      // Report & Referral Slip
      'referral_card_title': 'દર્દી રેફરલ કાર્ડ',
      'slip_title': 'દ્રષ્ટિ — ટેલી-રેટિના તપાસ અને રેફરલ સ્લિપ',
      'slip_subtitle': 'નેશનલ પ્રોગ્રામ ફોર કંટ્રોલ ઓફ બ્લાઇન્ડનેસ (NPCB) સહાય | SIH 2026',
      'slip_verified_title': 'જિલ્લા ટેલી-ઓપ્થેલ્મોલોજી દ્વારા પ્રમાણિત',
      'slip_urgency_urgent': 'તાત્કાલિક આંખના ડૉક્ટરને મળો',
      'slip_urgency_routine': 'દ્રષ્ટિને કોઈ ખતરો નથી • વાર્ષિક તપાસ જરૂરી',
      'slip_advice_urgent': 'હોસ્પિટલ સૂચના: રેટિનામાં ડાયાબિટીસની અસર જણાઈ છે. કૃપા કરીને 7-14 દિવસમાં જિલ્લા આંખના ડૉક્ટરનો સંપર્ક કરો.',
      'slip_advice_routine': 'સલાહ: હાલમાં કોઈ ગંભીર ખામી નથી. લોહીમાં સુગર નિયંત્રણમાં રાખો અને 12 મહિના પછી ફરી તપાસ કરાવો.',
      'slip_tips_title': 'દર્દી અને પરિવાર માટે મહત્વપૂર્ણ આરોગ્ય માર્ગદર્શન:',
      'slip_tip1_title': '1. બ્લડ સુગર નિયંત્રણ (HbA1c < 7.0%)',
      'slip_tip1_desc': 'દવા સમયસર લો. ત્રણ મહિનાની સુગર તપાસ 7% થી નીચે રાખો.',
      'slip_tip2_title': '2. બ્લડ પ્રેશર નિયંત્રણ (< 130/80)',
      'slip_tip2_desc': 'હાઈ બ્લડ પ્રેશર આંખની નાજુક નસોને નુકસાન પહોંચાડે છે.',
      'slip_tip3_title': '3. ઓછી ખાંડવાળો સંતુલિત ખોરાક',
      'slip_tip3_desc': 'લીલા શાકભાજી, ઓછું તેલ અને પૂરતું પાણી પીવો. ખાંડ ટાળો.',
      'slip_tip4_title': '4. નિયમિત રેટિના તપાસ',
      'slip_tip4_desc': 'શરૂઆતમાં કોઈ લક્ષણો દેખાતા નથી. નિયમિત તપાસથી જ આંખો સુરક્ષિત રહે છે.',
      'slip_footer_doc': 'પ્રમાણિત ટેલી-આંખના નિષ્ણાત: ડૉ. રાજેશ કુમાર, MD (ઓપ્થેલ્મોલોજી)',
      'slip_footer_notice': '*આ કમ્પ્યુટરાઇઝ્ડ ટેલી-સ્ક્રિનિંગ સ્લિપ છે, કોઈ ભૌતિક સહીની જરૂર નથી.',
      'slip_qr_label': 'QR ચકાસણી',
      'slip_print_btn': 'સ્લિપ પ્રિન્ટ કરો',
      'slip_share_btn': 'વોટ્સએપ પર મોકલો',
      'urgency_immediate': 'તાત્કાલિક: 7–14 દિવસમાં આંખના ડૉક્ટરને મળો',
      'urgency_routine': 'નિયમિત: 12 મહિના પછી વાર્ષિક તપાસ કરાવો',
      'advice_hba1c': 'HbA1c 7.0% થી નીચે રાખો',
      'advice_bp': 'બ્લડ પ્રેશર નિયંત્રણમાં રાખો (< 130/80)',
      'advice_diet': 'ઓછી ખાંડવાળો સંતુલિત ખોરાક લો',
      'print_pdf': 'પીડીએફ સ્લિપ ડાઉનલોડ કરો',
      'share_slip': 'વોટ્સએપ પર મોકલો',
    },

    'ta': {
      'app_title': 'திருஷ்டி (Drishti)',
      'tagline': 'கிராமப்புற இந்தியாவிற்கான விழித்திரை பரிசோதனை AI',
      'phc_screener': 'சுகாதார பணியாளர் (PHC)',
      'specialist': 'கண் மருத்துவர்',
      'switch_to_doctor': 'மருத்துவர் பக்கம்',
      'switch_to_screener': 'பணியாளர் பக்கம்',
      'audio_guide': 'ஒலி வழிகாட்டி',
      'audio_on': 'குரல் உதவி ஆன்',
      'audio_off': 'குரல் உதவி ஆஃப்',
      'select_language': 'மொழியைத் தேர்வு செய்க / Select Language',
      'language_subtitle': 'ஆரம்ப சுகாதார நிலையங்கள் மற்றும் ஆஷா பணியாளர்களுக்காக பிரத்யேகமானது',
      'sign_out': 'வெளியேறு',
      'sign_out_title': 'பணிநிலையத்திலிருந்து வெளியேறவா?',
      'sign_out_desc': 'உங்கள் ஆஃப்லைன் தரவு பாதுகாப்பாக சேமிக்கப்படும்.',
      'cancel': 'ரத்துசெய்',
      'cancel_session': 'அமர்வை ரத்துசெய்',
      'token_active': 'டோக்கன் செயலில் உள்ளது',
      'screener': 'பரிசோதகர்',
      'doctor': 'மருத்துவர்',
      'urgent_referrals': 'அவசர பரிந்துரைகள்',
      'review_next_case': 'அடுத்த நோயாளியை பரிசோதிக்கவும்',
      'open_review_queue': 'முழு பரிசீலனை வரிசையைத் திறக்கவும்',
      'recent_cases': 'சமீபத்திய வழக்குகள்',
      'no_pending_cases': 'பரிசீலனைக்கு நிலுவையில் உள்ள வழக்குகள் இல்லை.',
      'risk_high': 'அதிதீவிர ஆபத்து',
      'risk_low': 'குறைந்த ஆபத்து',
      'risk_moderate': 'மிதமான ஆபத்து',
      'risk_badge_high': 'அதிகம்',
      'risk_badge_low': 'குறைவு',
      'risk_badge_mod': 'மிதம்',
      'patient_prefix': 'நோயாளி',
      'level_prefix': 'நிலை',
      'no_screenings_today': 'இன்று இதுவரை எந்த புதிய பதிவும் இல்லை.',
      'model_probability': 'மாதிரி துல்லியம்',
      'calibrated_confidence': 'நம்பகத்தன்மை',
      'optical_quality': 'படத் தரம்',
      'softmax_probabilities': 'சாஃப்ட்மேக்ஸ் நிகழ்தகவு',
      'triage_recommendation': 'AI மருத்துவ பரிந்துரை',
      'neural_classification': 'விழித்திரை நரம்பு வகைப்பாடு',
      'sample_prefix': 'மாதிரி',
      'grading_in_progress': 'மதிப்பாய்வு நடக்கிறது',
      'awaiting_ai_grading': 'AI பகுப்பாய்வு காத்திருக்கிறது',
      'auto_calibrated': 'தானியங்கி அளவுத்திருத்தம்',
      'optimal': 'சிறந்தது',
      'high_risk_flag': 'மருத்துவருக்கு பரிந்துரைக்கப்பட்டது',
      'specialist_validated': 'மருத்துவர் சான்றளித்தது',

      // 3-Step Guided Flow Ribbon
      'step1_ribbon': '1. நோயாளி விவரங்கள் (Intake)',
      'step2_ribbon': '2. விழித்திரை படம் எடு (Photo)',
      'step3_ribbon': '3. முடிவு & பரிந்துரை சீட்டு (Result & Slip)',
      'step1_short': 'விவரம்',
      'step2_short': 'படம்',
      'step3_short': 'முடிவு',

      // Navigation
      'nav_dashboard': 'முகப்பு',
      'nav_intake': 'புதிய நோயாளி',
      'nav_patients': 'பட்டியல்',
      'nav_sync': 'ஒத்திசைவு',
      'nav_profile': 'சுயவிவரம்',
      'nav_queue': 'வரிசை',
      'nav_cases': 'அனைத்து வழக்குகள்',
      'nav_overview': 'மேற்பார்வை',
      'nav_reports': 'அறிக்கைகள்',

      // Dashboard
      'greeting_morning': 'காலை வணக்கம்',
      'greeting_afternoon': 'மதிய வணக்கம்',
      'greeting_evening': 'மாலை வணக்கம்',
      'stat_screened': 'பரிசோதிக்கப்பட்டவை',
      'stat_screened_sub': 'பதிவு செய்யப்பட்ட நோயாளிகள்',
      'stat_referable': 'பரிந்துரை தேவை',
      'stat_referable_sub': 'மருத்துவருக்கு பரிந்துரைக்கப்பட்டது',
      'stat_pending': 'மதிப்பாய்வு நிலுவை',
      'stat_pending_sub': 'வரிசையில் உள்ளது',
      'stat_completed': 'முடிந்தது',
      'stat_completed_sub': 'உறுதி செய்யப்பட்டது',
      'start_screening': '+ புதிய பரிசோதனை',
      'view_records': 'பதிவுகளைக் காண்க',
      'recent_screenings': 'சமீபத்திய பரிசோதனைகள்',
      'view_all': 'அனைத்தையும் காண்க',
      'quick_demo_test': '⚡ மாதிரி பரிசோதனை வழக்குகள்',
      'quick_demo_desc': 'கேமரா இல்லாமல் மாதிரி படங்களை உடனடியாக சோதிக்கவும்',

      // Intake
      'patient_demographics': 'நோயாளி விவரங்கள்',
      'patient_id': 'நோயாளி ID / டோக்கன்',
      'age': 'வயது (ஆண்டுகள்)',
      'gender': 'பாலினம்',
      'gender_female': 'பெண்',
      'gender_male': 'ஆண்',
      'gender_other': 'மற்றவை',
      'diabetes_duration': 'நீரிழிவு காலம் (ஆண்டுகள்)',
      'eye_selection': 'பரிசோதனைக்குரிய கண்',
      'right_eye': 'வலது கண் (OD)',
      'left_eye': 'இடது கண் (OS)',
      'od_subtitle': 'வலது கண் • Oculus Dexter',
      'os_subtitle': 'இடது கண் • Oculus Sinister',
      'proceed_capture': 'படம் எடுக்க தொடரவும்',
      'fill_demo': '⚡ மாதிரி நோயாளியை நிரப்பவும்',

      // Capture
      'retinal_acquisition': 'விழித்திரை படம் எடுத்தல்',
      'camera_capture': 'கேமரா மூலம் படம் எடு',
      'gallery_select': 'கோப்பிலிருந்து தேர்வு செய்',
      'reticle_guide': 'ஆப்டிக் டிஸ்க்கை மையத்தில் வைக்கவும்',
      'loaded_guide': 'படம் ஏற்றப்பட்டது • விழித்திரை பரப்பை சரிபார்க்கவும்',
      'clinical_samples_title': 'மாதிரி வழக்குகள் (SIH 2026 தரம்)',
      'confirm_quality': 'தரத்தை சரிபார்க்கவும்',
      'reset': 'மீட்டமைக்க',
      'optical_checklist_title': 'கேமரா படத் தர சரிபார்ப்பு:',
      'chk_clarity': 'தெளிவு: நன்று',
      'chk_light': 'வெளிச்சம்: போதுமானது',
      'chk_center': 'மையம்: நன்று',
      'speak_guidance': 'நோயாளிக்கு ஒலி வழிகாட்டல்',

      // Quality
      'quality_title': 'படத் தர பாதுகாப்பு வாயில்',
      'sharpness': 'தெளிவு மற்றும் கூர்மை',
      'illumination': 'வெளிச்சம் மற்றும் பிரகாசம்',
      'fov': 'கவரேஜ் பகுதி',
      'quality_good': 'சிறந்த தரம்',
      'quality_borderline': 'மிதமான தரம் (CLAHE மேம்படுத்தப்பட்டது)',
      'quality_ungradable': 'மங்கலான படம் — மீண்டும் படம் எடுக்கவும்',
      'proceed_inference': 'AI பகுப்பாய்வை தொடங்கவும்',
      'retake_image': 'மீண்டும் படம் எடுக்கவும்',

      // Results
      'ai_result_title': 'AI முடிவு ஆதரவு மதிப்பீடு',
      'level_0': 'பாதிப்பில்லை (இயல்பு)',
      'level_1': 'லேசான பாதிப்பு (Mild NPDR)',
      'level_2': 'மிதமான பாதிப்பு (Moderate NPDR)',
      'level_3': 'கடுமையான பாதிப்பு (Severe NPDR)',
      'level_4': 'அதிதீவிர பாதிப்பு (PDR)',
      'referable_yes': 'மருத்துவமனை பரிந்துரை தேவை',
      'referable_no': 'ஆண்டு பரிசோதனை போதுமானது',
      'view_xai': 'ஹீட்மேப்பைக் காண்க (Grad-CAM)',
      'view_report': 'அறிக்கை மற்றும் சீட்டைப் பார்க்கவும்',
      'new_screening': 'அடுத்த நோயாளியை பரிசோதிக்கவும்',
      'patient_slip_btn': 'நோயாளி பரிந்துரை சீட்டு',

      // Explainability
      'xai_title': 'காட்சி விளக்கம் (Grad-CAM ஹீட்மேப்)',
      'tab_original': 'அசல் படம்',
      'tab_gradcam': 'ஹீட்மேப்',
      'tab_overlay': 'மேலடுக்கு',
      'blend_opacity': 'ஹீட்மேப் ஒளிபுகாமை:',
      'lesion_guide_title': 'விழித்திரை பாதிப்பு வழிகாட்டி',
      'attended_structures': 'AI கவனித்த பகுதிகள்',

      // Report & Referral Slip
      'referral_card_title': 'நோயாளி பரிந்துரை அட்டை',
      'slip_title': 'திருஷ்டி — டெலி-விழித்திரை பரிசோதனை & பரிந்துரை சீட்டு',
      'slip_subtitle': 'தேசிய பார்வையிழப்பு தடுப்பு திட்டம் (NPCB) ஆதரவு | SIH 2026',
      'slip_verified_title': 'மாவட்ட கண் மருத்துவ சான்றளிக்கப்பட்டது',
      'slip_urgency_urgent': 'கண் மருத்துவரை உடனடியாக அணுகவும்',
      'slip_urgency_routine': 'பார்வைக்கு ஆபத்தில்லை • ஆண்டு பரிசோதனை போதுமானது',
      'slip_advice_urgent': 'மருத்துவமனை குறிப்பு: விழித்திரையில் பாதிப்பு கண்டறியப்பட்டுள்ளது. அடுத்த 7-14 நாட்களுக்குள் மாவட்ட கண் மருத்துவரை அணுகவும்.',
      'slip_advice_routine': 'ஆலோசனை: தற்போது தீவிர பாதிப்பு ஏதுமில்லை. இரத்த சர்க்கரையை கட்டுக்குள் வைத்து ஆண்டுதோறும் பரிசோதிக்கவும்.',
      'slip_tips_title': 'நோயாளி மற்றும் குடும்பத்திற்கான முக்கிய வழிகாட்டுதல்:',
      'slip_tip1_title': '1. இரத்த சர்க்கரை கட்டுப்பாடு (HbA1c < 7%)',
      'slip_tip1_desc': 'மருந்துகளை தவறாமல் உட்கொள்ளவும். HbA1c அளவை 7% க்குள் பராமரிக்கவும்.',
      'slip_tip2_title': '2. இரத்த அழுத்தம் கட்டுப்பாடு (< 130/80)',
      'slip_tip2_desc': 'உயர் இரத்த அழுத்தம் விழித்திரை இரத்த நாளங்களை பாதிக்கும்.',
      'slip_tip3_title': '3. சமச்சீர் சர்க்கரை குறைவான உணவு',
      'slip_tip3_desc': 'கீரை வகைகள், குறைந்த எண்ணெய், பழங்கள் மற்றும் போதிய தண்ணீர் அருந்தவும்.',
      'slip_tip4_title': '4. வழக்கமான விழித்திரை பரிசோதனை',
      'slip_tip4_desc': 'தொடக்கத்தில் வலி அல்லது அறிகுறி இருக்காது. வழக்கமான பரிசோதனையே பார்வை காக்கும்.',
      'slip_footer_doc': 'சரிபார்க்கப்பட்ட கண் மருத்துவர்: டாக்டர் ராஜேஷ் குமார், MD (கண் மருத்துவம்)',
      'slip_footer_notice': '*இது கணினி சரிபார்க்கப்பட்ட டெலி-ஸ்கிரீனிங் சீட்டு, கையொப்பம் தேவையில்லை.',
      'slip_qr_label': 'QR சரிபார்ப்பு',
      'slip_print_btn': 'சீட்டை அச்சிடுக',
      'slip_share_btn': 'வாட்ஸ்அப்பில் அனுப்பவும்',
      'urgency_immediate': 'அவசரம்: 7–14 நாட்களுக்குள் கண் மருத்துவரை அணுகவும்',
      'urgency_routine': 'வழக்கமானது: 12 மாதங்களில் ஆண்டு பரிசோதனை',
      'advice_hba1c': 'HbA1c 7.0% க்குள் பராமரிக்கவும்',
      'advice_bp': 'இரத்த அழுத்தத்தைக் கட்டுப்படுத்தவும் (< 130/80)',
      'advice_diet': 'சமச்சீர் சர்க்கரை குறைவான உணவு உண்ணவும்',
      'print_pdf': 'PDF சீட்டை பதிவிறக்கவும்',
      'share_slip': 'வாட்ஸ்அப்பில் பகிரவும்',
    },

    'te': {
      'app_title': 'దృష్టి (Drishti)',
      'tagline': 'గ్రామీణ భారతదేశం కోసం AI రెటీనా స్క్రీనింగ్',
      'phc_screener': 'ఆరోగ్య కార్యకర్త (PHC)',
      'specialist': 'నేత్ర నిపుణుడు (డాక్టర్)',
      'switch_to_doctor': 'డాక్టర్ పోర్టల్',
      'switch_to_screener': 'ఆరోగ్య కార్యకర్త పోర్టల్',
      'audio_guide': 'వాయిస్ గైడ్',
      'audio_on': 'వాయిస్ గైడ్ ఆన్',
      'audio_off': 'వాయిస్ గైడ్ ఆఫ్',
      'select_language': 'భాషను ఎంచుకోండి / Select Language',
      'language_subtitle': 'ప్రాథమిక ఆరోగ్య కేంద్రాలు & ఆశా వర్కర్ల కోసం ప్రత్యేక రూపకల్పన',
      'sign_out': 'లాగ్ అవుట్',
      'sign_out_title': 'వర్క్‌స్టేషన్ నుండి లాగ్ అవుట్ చేయాలా?',
      'sign_out_desc': 'మీ స్థానిక ఆఫ్‌లైన్ డేటా సురక్షితంగా సేవ్ చేయబడుతుంది.',
      'cancel': 'రద్దు చేయండి',
      'cancel_session': 'సెషన్ రద్దు చేయండి',
      'token_active': 'టోకెన్ యాక్టివ్',
      'screener': 'స్క్రీనర్',
      'doctor': 'డాక్టర్',
      'urgent_referrals': 'అత్యవసర రిఫరల్స్',
      'review_next_case': 'తదుపరి రోగిని సమీక్షించండి',
      'open_review_queue': 'పూర్తి సమీక్ష క్యూను తెరవండి',
      'recent_cases': 'ఇటీవలి కేసులు',
      'no_pending_cases': 'సమీక్ష కోసం వేచి ఉన్న కేసులు లేవు.',
      'risk_high': 'అధిక ప్రమాదం',
      'risk_low': 'తక్కువ ప్రమాదం',
      'risk_moderate': 'మితమైన ప్రమాదం',
      'risk_badge_high': 'అధికం',
      'risk_badge_low': 'తక్కువ',
      'risk_badge_mod': 'మితం',
      'patient_prefix': 'రోగి',
      'level_prefix': 'స్థాయి',
      'no_screenings_today': 'ఈ రోజు ఇంకా కొత్త పరీక్షలు నమోదు కాలేదు.',
      'model_probability': 'మోడల్ ఖచ్చితత్వం సంభావ్యత',
      'calibrated_confidence': 'క్యాలిబ్రేటెడ్ విశ్వసనీయత',
      'optical_quality': 'ఆప్టికల్ నాణ్యత',
      'softmax_probabilities': 'సాఫ్ట్‌మాక్స్ తరగతి సంభావ్యతలు',
      'triage_recommendation': 'AI క్లినికల్ రిఫరల్ సిఫార్సు',
      'neural_classification': 'న్యూరల్ రెటినోపతి వర్గీకరణ',
      'sample_prefix': 'నమూనా',
      'grading_in_progress': 'పరీక్ష పురోగతిలో ఉంది',
      'awaiting_ai_grading': 'AI విశ్లేషణ కోసం వేచి ఉంది',
      'auto_calibrated': 'స్వయం-క్యాలిబ్రేటెడ్',
      'optimal': 'ఉత్తమమైనది',
      'high_risk_flag': 'నిపుణుడికి సిఫార్సు చేయబడింది',
      'specialist_validated': 'నిపుణుడిచే ధృవీకరించబడింది',

      // 3-Step Guided Flow Ribbon
      'step1_ribbon': '1. రోగి వివరాలు (Intake)',
      'step2_ribbon': '2. రెటీనా ఫోటో తీయండి (Photo)',
      'step3_ribbon': '3. ఫలితం & రిఫరల్ స్లిప్ (Result & Slip)',
      'step1_short': 'వివరాలు',
      'step2_short': 'ఫోటో',
      'step3_short': 'ఫలితం',

      // Navigation
      'nav_dashboard': 'డాష్‌బోర్డ్',
      'nav_intake': 'కొత్త రోగి',
      'nav_patients': 'రోగుల జాబితా',
      'nav_sync': 'గ్రామీణ సమకాలీకరణ',
      'nav_profile': 'ప్రొఫైల్',
      'nav_queue': 'సమీక్ష క్యూ',
      'nav_cases': 'అన్ని కేసులు',
      'nav_overview': 'సమీక్ష',
      'nav_reports': 'నివేదికలు',

      // Dashboard
      'greeting_morning': 'శుభోదయం',
      'greeting_afternoon': 'శుభ మధ్యాహ్నం',
      'greeting_evening': 'శుభ సాయంత్రం',
      'stat_screened': 'మొత్తం పరీక్షించినవి',
      'stat_screened_sub': 'నమోదైన రోగులు',
      'stat_referable': 'రిఫరల్ అవసరం',
      'stat_referable_sub': 'డాక్టర్‌కు సూచించబడింది',
      'stat_pending': 'సమీక్ష పెండింగ్',
      'stat_pending_sub': 'క్యూలో ఉంది',
      'stat_completed': 'పూర్తయింది',
      'stat_completed_sub': 'నిర్ధారించబడింది',
      'start_screening': '+ కొత్త రెటీనా పరీక్ష ప్రారంభించండి',
      'view_records': 'రోగి రికార్డులను చూడండి',
      'recent_screenings': 'ఇటీవలి పరీక్షలు',
      'view_all': 'అన్నీ చూడండి',
      'quick_demo_test': '⚡ డెమో టెస్ట్ నమూనాలు',
      'quick_demo_desc': 'కెమెరా లేకుండా నమూనా చిత్రాలను పరీక్షించండి',

      // Intake
      'patient_demographics': 'రోగి వివరాలు',
      'patient_id': 'రోగి ID / టోకెన్ నంబర్',
      'age': 'వయస్సు (సంవత్సరాలు)',
      'gender': 'లింగం',
      'gender_female': 'స్త్రీ',
      'gender_male': 'పురుషుడు',
      'gender_other': 'ఇతర',
      'diabetes_duration': 'మధుమేహం వ్యవధి (సంవత్సరాలు)',
      'eye_selection': 'పరీక్ష కోసం కంటిని ఎంచుకోండి',
      'right_eye': 'కుడి కన్ను (OD)',
      'left_eye': 'ఎడమ కన్ను (OS)',
      'od_subtitle': 'కుడి కన్ను • Oculus Dexter',
      'os_subtitle': 'ఎడమ కన్ను • Oculus Sinister',
      'proceed_capture': 'ఫోటో తీయడానికి కొనసాగండి',
      'fill_demo': '⚡ డెమో రోగి వివరాలు నింపండి',

      // Capture
      'retinal_acquisition': 'రెటీనా ఫోటో సేకరణ',
      'camera_capture': 'కెమెరాతో ఫోటో తీయండి',
      'gallery_select': 'ఫైల్ నుండి ఎంచుకోండి',
      'reticle_guide': 'ఆప్టిక్ డిస్క్‌ను మధ్యలో ఉంచండి',
      'loaded_guide': 'ఫోటో లోడ్ అయింది • రెటీనా ప్రాంతాన్ని తనిఖీ చేయండి',
      'clinical_samples_title': 'క్లినికల్ టెస్ట్ కేసులు (SIH 2026 బెంచ్‌మార్క్)',
      'confirm_quality': 'నాణ్యతను నిర్ధారించండి',
      'reset': 'రీసెట్',
      'optical_checklist_title': 'కెమెరా ఫోటో నాణ్యత తనిఖీ:',
      'chk_clarity': 'స్పష్టత: బాగుంది',
      'chk_light': 'వెలుతురు: సరిపోతుంది',
      'chk_center': 'కేంద్రం: సరైనది',
      'speak_guidance': 'రోగికి వాయిస్ గైడెన్స్ వినిపించండి',

      // Quality
      'quality_title': 'నాణ్యతా భద్రతా గేట్',
      'sharpness': 'ఫోకస్ మరియు స్పష్టత',
      'illumination': 'వెలుతురు మరియు ప్రకాశం',
      'fov': 'కవరేజ్ ప్రాంతం',
      'quality_good': 'ఉత్తమ నాణ్యత',
      'quality_borderline': 'మితమైన నాణ్యత (CLAHE మెరుగుదల)',
      'quality_ungradable': 'మసక చిత్రం — దయచేసి మళ్లీ ఫోటో తీయండి',
      'proceed_inference': 'AI విశ్లేషణను ప్రారంభించండి',
      'retake_image': 'మళ్లీ ఫోటో తీయండి',

      // Results
      'ai_result_title': 'AI నిర్ణయ మద్దతు ఫలితం',
      'level_0': 'సాధారణం (ఎటువంటి ప్రభావం లేదు)',
      'level_1': 'తేలికపాటి ప్రభావం (Mild NPDR)',
      'level_2': 'మితమైన ప్రభావం (Moderate NPDR)',
      'level_3': 'తీవ్రమైన ప్రభావం (Severe NPDR)',
      'level_4': 'అత్యంత తీవ్ర ప్రభావం (తక్షణ రిఫరల్)',
      'referable_yes': 'ఆసుపత్రి రిఫరల్ అవసరం',
      'referable_no': 'వార్షిక పరీక్ష సరిపోతుంది',
      'view_xai': 'హీట్‌మ్యాప్ చూడండి (Grad-CAM)',
      'view_report': 'పూర్తి నివేదిక & స్లిప్ చూడండి',
      'new_screening': 'తదుపరి రోగిని పరీక్షించండి',
      'patient_slip_btn': 'రోగి రిఫరల్ స్లిప్',

      // Explainability
      'xai_title': 'విజువల్ వివరణ (Grad-CAM హీట్‌మ్యాప్)',
      'tab_original': 'అసలు చిత్రం',
      'tab_gradcam': 'హీట్‌మ్యాప్',
      'tab_overlay': 'ఓవర్‌లే',
      'blend_opacity': 'హీట్‌మ్యాప్ పారదర్శకత:',
      'lesion_guide_title': 'రెటీనా నష్టం గైడ్',
      'attended_structures': 'AI గుర్తించిన ప్రాంతాలు',

      // Report & Referral Slip
      'referral_card_title': 'రోగి రిఫరల్ & సలహా కార్డు',
      'slip_title': 'దృష్టి — టెలి-రెటీనా స్క్రీనింగ్ & రిఫరల్ స్లిప్',
      'slip_subtitle': 'నేషనల్ ప్రోగ్రామ్ ఫర్ కంట్రోల్ ఆఫ్ బ్లైండ్‌నెస్ (NPCB) మద్దతు | SIH 2026',
      'slip_verified_title': 'జిల్లా టెలి-ఆప్తాల్మాలజీ ద్వారా ధృవీకరించబడింది',
      'slip_urgency_urgent': 'నేత్ర నిపుణుడిని వెంటనే సంప్రదించండి',
      'slip_urgency_routine': 'దృష్టికి ఎటువంటి ప్రమాదం లేదు • వార్షిక పరీక్ష సరిపోతుంది',
      'slip_advice_urgent': 'ఆసుపత్రి సూచన: రెటీనాలో మధుమేహ మార్పులు కనుగొనబడ్డాయి. దయచేసి 7-14 రోజుల్లో జిల్లా నేత్ర నిపుణుడిని సంప్రదించండి.',
      'slip_advice_routine': 'సలహా: ప్రస్తుతం ఎటువంటి తీవ్ర నష్టం లేదు. రక్తంలో చక్కెరను అదుపులో ఉంచుకోండి మరియు 12 నెలల తర్వాత మళ్లీ పరీక్షించుకోండి.',
      'slip_tips_title': 'రోగి మరియు కుటుంబం కోసం ముఖ్యమైన ఆరోగ్య మార్గదర్శకాలు:',
      'slip_tip1_title': '1. రక్తంలో చక్కెర నియంత్రణ (HbA1c < 7.0%)',
      'slip_tip1_desc': 'మందులు క్రమం తప్పకుండా తీసుకోండి. 3 నెలల సగటు HbA1c 7% లోపు ఉంచండి.',
      'slip_tip2_title': '2. రక్తపోటు నియంత్రణ (< 130/80 mmHg)',
      'slip_tip2_desc': 'అధిక రక్తపోటు కంటి రక్తనాళాలను దెబ్బతీస్తుంది.',
      'slip_tip3_title': '3. సమతుల్య ఆహారం',
      'slip_tip3_desc': 'ఆకుకూరలు, తక్కువ నూనె మరియు తగినంత నీరు త్రాగాలి. చక్కెరను నివారించండి.',
      'slip_tip4_title': '4. సాధారణ రెటీనా పరీక్ష',
      'slip_tip4_desc': 'ప్రారంభంలో ఎటువంటి లక్షణాలు ఉండవు. క్రమబద్ధమైన పరీక్షలే దృష్టిని కాపాడతాయి.',
      'slip_footer_doc': 'ధృవీకరించబడిన టెలి-నేత్ర నిపుణుడు: డాక్టర్ రాజేష్ కుమార్, MD (ఆప్తాల్మాలజీ)',
      'slip_footer_notice': '*ఇది కంప్యూటరైజ్డ్ టెలి-స్క్రీనింగ్ స్లిప్, భౌతిక సంతకం అవసరం లేదు.',
      'slip_qr_label': 'QR ధృవీకరణ',
      'slip_print_btn': 'స్లిప్ ప్రింట్ చేయండి',
      'slip_share_btn': 'వాట్సాప్‌లో పంపండి',
      'urgency_immediate': 'అత్యవసరం: 7–14 రోజుల్లో నేత్ర నిపుణుడిని కలవండి',
      'urgency_routine': 'సాధారణం: 12 నెలల్లో వార్షిక పరీక్ష',
      'advice_hba1c': 'HbA1c 7.0% లోపు ఉంచండి',
      'advice_bp': 'రక్తపోటును నియంత్రణలో ఉంచండి (< 130/80)',
      'advice_diet': 'తక్కువ చక్కెర గల సమతుల్య ఆహారం తీసుకోండి',
      'print_pdf': 'PDF స్లిప్ డౌన్‌లోడ్ చేయండి',
      'share_slip': 'వాట్సాప్‌లో పంచుకోండి',
    },

    'bn': {
      'app_title': 'দৃষ্টি (Drishti)',
      'tagline': 'গ্রামীণ ভারতের জন্য ব্যাখ্যাযোগ্য এআই রেটিনা পরীক্ষা',
      'phc_screener': 'স্বাস্থ্যকর্মী (PHC)',
      'specialist': 'চক্ষু বিশেষজ্ঞ (ডাক্তার)',
      'switch_to_doctor': 'ডাক্তার পোর্টাল',
      'switch_to_screener': 'স্বাস্থ্যকর্মী পোর্টাল',
      'audio_guide': 'ভয়েস গাইড',
      'audio_on': 'ভয়েস সহায়তা চালু',
      'audio_off': 'ভয়েস সহায়তা বন্ধ',
      'select_language': 'ভাষা নির্বাচন করুন / Select Language',
      'language_subtitle': 'প্রাথমিক স্বাস্থ্য কেন্দ্র ও আশা কর্মীদের জন্য বিশেষভাবে উপযোগী',
      'sign_out': 'লগ আউট',
      'sign_out_title': 'ওয়ার্কস্টেশন থেকে লগ আউট করবেন?',
      'sign_out_desc': 'আপনার স্থানীয় অফলাইন ডেটা নিরাপদে সংরক্ষিত থাকবে।',
      'cancel': 'বাতিল করুন',
      'cancel_session': 'সেশন বাতিল করুন',
      'token_active': 'টোকেন সক্রিয়',
      'screener': 'স্ক্রিনার',
      'doctor': 'ডাক্তার',
      'urgent_referrals': 'জরুরি রেফারেল',
      'review_next_case': 'পরবর্তী রোগী পর্যালোচনা করুন',
      'open_review_queue': 'সম্পূর্ণ পর্যালোচনা তালিকা খুলুন',
      'recent_cases': 'সাম্প্রতিক কেস',
      'no_pending_cases': 'পর্যালোচনার জন্য কোনো কেস অপেক্ষমাণ নেই।',
      'risk_high': 'উচ্চ ঝুঁকি',
      'risk_low': 'কম ঝুঁকি',
      'risk_moderate': 'মাঝারি ঝুঁকি',
      'risk_badge_high': 'উচ্চ',
      'risk_badge_low': 'কম',
      'risk_badge_mod': 'মাঝারি',
      'patient_prefix': 'রোগী',
      'level_prefix': 'স্তর',
      'no_screenings_today': 'আজ এখনও পর্যন্ত কোনো নতুন পরীক্ষা নথিভুক্ত হয়নি।',
      'model_probability': 'মডেল নির্ভুলতা সম্ভাবনা',
      'calibrated_confidence': 'ক্যালিব্রেটেড আত্মবিশ্বাস',
      'optical_quality': 'অপটিক্যাল গুণমান',
      'softmax_probabilities': 'সফ্টম্যাক্স শ্রেণী সম্ভাবনা',
      'triage_recommendation': 'এআই ক্লিনিক্যাল রেফারেল সুপারিশ',
      'neural_classification': 'নিউরাল রেটিনোপ্যাথি শ্রেণিবিন্যাস',
      'sample_prefix': 'নমুনা',
      'grading_in_progress': 'পরীক্ষা চলছে',
      'awaiting_ai_grading': 'এআই বিশ্লেষণের অপেক্ষায়',
      'auto_calibrated': 'স্বয়ংক্রিয়-ক্যালিব্রেটেড',
      'optimal': 'সেরা',
      'high_risk_flag': 'বিশেষজ্ঞের জন্য চিহ্নিত',
      'specialist_validated': 'বিশেষজ্ঞ কর্তৃক যাচাইকৃত',

      // 3-Step Guided Flow Ribbon
      'step1_ribbon': '1. রোগীর তথ্য (Intake)',
      'step2_ribbon': '2. রেটিনা ছবি তুলুন (Photo)',
      'step3_ribbon': '3. ফলাফল ও রেফারেল স্লিপ (Result & Slip)',
      'step1_short': 'তথ্য',
      'step2_short': 'ছবি',
      'step3_short': 'ফলাফল',

      // Navigation
      'nav_dashboard': 'ড্যাশবোর্ড',
      'nav_intake': 'নতুন রোগী',
      'nav_patients': 'রোগী তালিকা',
      'nav_sync': 'গ্রামীণ সিঙ্ক',
      'nav_profile': 'প্রোফাইল',
      'nav_queue': 'পর্যালোচনা সারি',
      'nav_cases': 'সকল কেস',
      'nav_overview': 'পর্যালোচনা',
      'nav_reports': 'প্রতিবেদন',

      // Dashboard
      'greeting_morning': 'সুপ্রভাত',
      'greeting_afternoon': 'শুভ অপরাহ্ন',
      'greeting_evening': 'শুভ সন্ধ্যা',
      'stat_screened': 'মোট পরীক্ষিত',
      'stat_screened_sub': 'নিবন্ধিত রোগী',
      'stat_referable': 'রেফারেল প্রয়োজন',
      'stat_referable_sub': 'ডাক্তারের কাছে পাঠানো হয়েছে',
      'stat_pending': 'পর্যালোচনা বাকি',
      'stat_pending_sub': 'সারিতে আছে',
      'stat_completed': 'সম্পন্ন',
      'stat_completed_sub': 'যাচাইকৃত',
      'start_screening': '+ নতুন রেটিনা পরীক্ষা শুরু করুন',
      'view_records': 'রোগীর রেকর্ড দেখুন',
      'recent_screenings': 'সাম্প্রতিক পরীক্ষাসমূহ',
      'view_all': 'সব দেখুন',
      'quick_demo_test': '⚡ নমুনা পরীক্ষা কেস',
      'quick_demo_desc': 'ক্যামেরা ছাড়াই নমুনা ছবি পরীক্ষা করুন',

      // Intake
      'patient_demographics': 'রোগীর বিবরণ',
      'patient_id': 'রোগী ID / টোকেন নম্বর',
      'age': 'বয়স (বছর)',
      'gender': 'লিঙ্গ',
      'gender_female': 'মহিলা',
      'gender_male': 'পুরুষ',
      'gender_other': 'অন্যান্য',
      'diabetes_duration': 'ডায়াবেটিসের মেয়াদ (বছর)',
      'eye_selection': 'পরীক্ষার জন্য চোখ নির্বাচন করুন',
      'right_eye': 'ডান চোখ (OD)',
      'left_eye': 'বাম চোখ (OS)',
      'od_subtitle': 'ডান চোখ • Oculus Dexter',
      'os_subtitle': 'বাম চোখ • Oculus Sinister',
      'proceed_capture': 'ছবি তুলতে এগিয়ে যান',
      'fill_demo': '⚡ ডেমো রোগী পূরণ করুন',

      // Capture
      'retinal_acquisition': 'রেটিনা ছবি গ্রহণ',
      'camera_capture': 'ক্যামেরা দিয়ে ছবি তুলুন',
      'gallery_select': 'ফাইল থেকে বেছে নিন',
      'reticle_guide': 'অপটিক ডিস্ক কেন্দ্রে রাখুন',
      'loaded_guide': 'ছবি লোড হয়েছে • রেটিনা এলাকা পরীক্ষা করুন',
      'clinical_samples_title': 'ক্লিনিক্যাল টেস্ট কেস (SIH 2026 মান)',
      'confirm_quality': 'গুণমান যাচাই ও নিশ্চিত করুন',
      'reset': 'রিসেট',
      'optical_checklist_title': 'ক্যামেরা ছবির গুণমান যাচাই:',
      'chk_clarity': 'স্পষ্টতা: ভালো',
      'chk_light': 'আলো: পর্যাপ্ত',
      'chk_center': 'কেন্দ্র: সঠিক',
      'speak_guidance': 'রোগীকে ভয়েস গাইডেন্স শোনান',

      // Quality
      'quality_title': 'ছবির গুণমান নিরাপত্তা গেট',
      'sharpness': 'ফোকাস এবং স্পষ্টতা',
      'illumination': 'আলো ও উজ্জ্বলতা',
      'fov': 'কভারেজ এলাকা',
      'quality_good': 'চমৎকার গুণমান',
      'quality_borderline': 'মাঝারি (CLAHE উন্নত)',
      'quality_ungradable': 'অস্পষ্ট ছবি — দয়া করে আবার ছবি তুলুন',
      'proceed_inference': 'এআই বিশ্লেষণ শুরু করুন',
      'retake_image': 'আবার ছবি তুলুন',

      // Results
      'ai_result_title': 'এআই সিদ্ধান্ত সহায়তা মূল্যায়ন',
      'level_0': 'স্বাভাবিক (কোনো ক্ষতি নেই)',
      'level_1': 'সামান্য প্রভাব (Mild NPDR)',
      'level_2': 'মাঝারি প্রভাব (Moderate NPDR)',
      'level_3': 'মারাত্মক প্রভাব (Severe NPDR)',
      'level_4': 'অতি-মারাত্মক প্রভাব (জরুরি রেফারেল)',
      'referable_yes': 'হাসপাতাল রেফারেল প্রয়োজন',
      'referable_no': 'বার্ষিক পরীক্ষা যথেষ্ট',
      'view_xai': 'হিটম্যাপ দেখুন (Grad-CAM)',
      'view_report': 'সম্পূর্ণ রিপোর্ট ও স্লিপ দেখুন',
      'new_screening': 'পরবর্তী রোগী পরীক্ষা করুন',
      'patient_slip_btn': 'রোগী রেফারেল স্লিপ',

      // Explainability
      'xai_title': 'ভিজ্যুয়াল ব্যাখ্যা (Grad-CAM হিটম্যাপ)',
      'tab_original': 'আসল ছবি',
      'tab_gradcam': 'হিটম্যাপ',
      'tab_overlay': 'ওভারলে',
      'blend_opacity': 'হিটম্যাপ স্বচ্ছতা:',
      'lesion_guide_title': 'রেটিনা ক্ষতি গাইড',
      'attended_structures': 'এআই চিহ্নিত এলাকা',

      // Report & Referral Slip
      'referral_card_title': 'রোগী পরামর্শ ও রেফারেল কার্ড',
      'slip_title': 'দৃষ্টি — টেলি-রেটিনা স্ক্রীনিং ও রেফারেল স্লিপ',
      'slip_subtitle': 'জাতীয় অন্ধত্ব নিয়ন্ত্রণ কর্মসূচি (NPCB) সহায়তা | SIH 2026',
      'slip_verified_title': 'জেলা টেলি-চক্ষুবিজ্ঞান দ্বারা যাচাইকৃত',
      'slip_urgency_urgent': 'জরুরি চক্ষু বিশেষজ্ঞের পরামর্শ নিন',
      'slip_urgency_routine': 'দৃষ্টিতে কোনো তাৎক্ষণিক বিপদ নেই • বার্ষিক পরীক্ষা আবশ্যক',
      'slip_advice_urgent': 'হাসপাতাল নির্দেশ: রেটিনায় ডায়াবেটিসের পরিবর্তন লক্ষ্য করা গেছে। দয়া করে আগামী ৭-১৪ দিনের মধ্যে জেলা চক্ষু বিশেষজ্ঞের সাথে দেখা করুন।',
      'slip_advice_routine': 'পরামর্শ: বর্তমানে কোনো মারাত্মক ক্ষতি নেই। রক্তে সুগার নিয়ন্ত্রণে রাখুন এবং ১২ মাস পর আবার পরীক্ষা করান।',
      'slip_tips_title': 'রোগী এবং পরিবারের জন্য গুরুত্বপূর্ণ স্বাস্থ্য নির্দেশিকা:',
      'slip_tip1_title': '১. রক্তে সুগার নিয়ন্ত্রণ (HbA1c < ৭.০%)',
      'slip_tip1_desc': 'নিয়মিত ওষুধ নিন। ৩ মাসের গড় HbA1c ৭% এর নিচে রাখুন।',
      'slip_tip2_title': '২. রক্তচাপ নিয়ন্ত্রণ (< ১৩০/৮০ mmHg)',
      'slip_tip2_desc': 'উচ্চ রক্তচাপ চোখের রক্তনালীকে ক্ষতিগ্রস্ত করে।',
      'slip_tip3_title': '৩. সুষম কম চিনির খাবার',
      'slip_tip3_desc': 'সবুজ শাকসবজি, কম তেল এবং পর্যাপ্ত জল পান করুন। চিনি বর্জন করুন।',
      'slip_tip4_title': '৪. নিয়মিত রেটিনা পরীক্ষা',
      'slip_tip4_desc': 'শুরুতে কোনো লক্ষণ থাকে না। নিয়মিত পরীক্ষাই দৃষ্টি রক্ষা করে।',
      'slip_footer_doc': 'যাচাইকৃত টেলি-চক্ষু বিশেষজ্ঞ: ডাঃ রাজেশ কুমার, MD (চক্ষুবিজ্ঞান)',
      'slip_footer_notice': '*এটি কম্পিউটারাইজড টেলি-স্ক্রীনিং স্লিপ, কোনো শারীরিক স্বাক্ষরের প্রয়োজন নেই।',
      'slip_qr_label': 'QR যাচাই',
      'slip_print_btn': 'স্লিপ প্রিন্ট করুন',
      'slip_share_btn': 'হোয়াটসঅ্যাপে পাঠান',
      'urgency_immediate': 'জরুরি: ৭–১৪ দিনের মধ্যে চক্ষু বিশেষজ্ঞের সাথে যোগাযোগ করুন',
      'urgency_routine': 'নিয়মিত: ১২ মাসের মধ্যে বার্ষিক পরীক্ষা',
      'advice_hba1c': 'HbA1c ৭.০% এর নিচে রাখুন',
      'advice_bp': 'রক্তচাপ নিয়ন্ত্রণে রাখুন (< ১৩০/৮০)',
      'advice_diet': 'কম শর্করাযুক্ত সুষম খাদ্য গ্রহণ করুন',
      'print_pdf': 'পিডিএফ স্লিপ ডাউনলোড করুন',
      'share_slip': 'হোয়াটসঅ্যাপে শেয়ার করুন',
    },

    'kn': {
      'app_title': 'ದೃಷ್ಟಿ (Drishti)',
      'tagline': 'ಗ್ರಾಮೀಣ ಭಾರತಕ್ಕಾಗಿ AI ರೆಟಿನಾ ತಪಾಸಣೆ',
      'phc_screener': 'ಆರೋಗ್ಯ ಕಾರ್ಯಕರ್ತ (PHC)',
      'specialist': 'ನೇತ್ರ ತಜ್ಞ (ವೈದ್ಯರು)',
      'switch_to_doctor': 'ವೈದ್ಯರ ಪೋರ್ಟಲ್',
      'switch_to_screener': 'ಆರೋಗ್ಯ ಕಾರ್ಯಕರ್ತರ ಪೋರ್ಟಲ್',
      'audio_guide': 'ಧ್ವನಿ ಮಾರ್ಗದರ್ಶಿ',
      'audio_on': 'ಧ್ವನಿ ಸಹಾಯ ಆನ್',
      'audio_off': 'ಧ್ವನಿ ಸಹಾಯ ಆಫ್',
      'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ / Select Language',
      'language_subtitle': 'ಪ್ರಾಥಮಿಕ ಆರೋಗ್ಯ ಕೇಂದ್ರಗಳು ಮತ್ತು ಆಶಾ ಕಾರ್ಯಕರ್ತರಿಗೆ ವಿಶೇಷವಾಗಿ ಸಿದ್ಧಪಡಿಸಲಾಗಿದೆ',
      'sign_out': 'ಸೈನ್ ಔಟ್',
      'sign_out_title': 'ವರ್ಕ್‌ಸ್ಟೇಷನ್‌ನಿಂದ ಸೈನ್ ಔಟ್ ಮಾಡುವುದೇ?',
      'sign_out_desc': 'ನಿಮ್ಮ ಸ್ಥಳೀಯ ಆಫ್‌ಲೈನ್ ಡೇಟಾವನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಸಂಗ್ರಹಿಸಲಾಗುತ್ತದೆ.',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'cancel_session': 'ಸೆಷನ್ ರದ್ದುಮಾಡಿ',
      'token_active': 'ಟೋಕನ್ ಸಕ್ರಿಯ',
      'screener': 'ಸ್ಕ್ರೀನರ್',
      'doctor': 'ವೈದ್ಯರು',
      'urgent_referrals': 'ತುರ್ತು ರೆಫರಲ್‌ಗಳು',
      'review_next_case': 'ಮುಂದಿನ ರೋಗಿಯನ್ನು ಪರಿಶೀಲಿಸಿ',
      'open_review_queue': 'ಸಂಪೂರ್ಣ ಪರಿಶೀಲನಾ ಪಟ್ಟಿ ತೆರೆಯಿರಿ',
      'recent_cases': 'ಇತ್ತೀಚಿನ ಪ್ರಕರಣಗಳು',
      'no_pending_cases': 'ಪರಿಶೀಲನೆಗಾಗಿ ಯಾವುದೇ ಪ್ರಕರಣಗಳು ಬಾಕಿ ಇಲ್ಲ.',
      'risk_high': 'ಹೆಚ್ಚಿನ ಅಪಾಯ',
      'risk_low': 'ಕಡಿಮೆ ಅಪಾಯ',
      'risk_moderate': 'ಮಧ್ಯಮ ಅಪಾಯ',
      'risk_badge_high': 'ಹೆಚ್ಚು',
      'risk_badge_low': 'ಕಡಿಮೆ',
      'risk_badge_mod': 'ಮಧ್ಯಮ',
      'patient_prefix': 'ರೋಗಿ',
      'level_prefix': 'ಹಂತ',
      'no_screenings_today': 'ಇಂದು ಇದುವರೆಗೆ ಯಾವುದೇ ಹೊಸ ತಪಾಸಣೆ ದಾಖಲಾಗಿಲ್ಲ.',
      'model_probability': 'ಮಾದರಿ ನಿಖರತೆ ಸಂಭವನೀಯತೆ',
      'calibrated_confidence': 'ಕ್ಯಾಲಿಬ್ರೇಟೆಡ್ ವಿಶ್ವಾಸಾರ್ಹತೆ',
      'optical_quality': 'ಆಪ್ಟಿಕಲ್ ಗುಣಮಟ್ಟ',
      'softmax_probabilities': 'ಸಾಫ್ಟ್‌ಮ್ಯಾಕ್ಸ್ ವರ್ಗ ಸಂಭವನೀಯತೆಗಳು',
      'triage_recommendation': 'AI ಕ್ಲಿನಿಕಲ್ ರೆಫರಲ್ ಶಿಫಾರಸು',
      'neural_classification': 'ನ್ಯೂರಲ್ ರೆಟಿನೋಪತಿ ವರ್ಗೀಕರಣ',
      'sample_prefix': 'ಮಾದರಿ',
      'grading_in_progress': 'ತಪಾಸಣೆ ಪ್ರಗತಿಯಲ್ಲಿದೆ',
      'awaiting_ai_grading': 'AI ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ',
      'auto_calibrated': 'ಸ್ವಯಂ-ಕ್ಯಾಲಿಬ್ರೇಟೆಡ್',
      'optimal': 'ಉತ್ತಮ',
      'high_risk_flag': 'ತಜ್ಞರಿಗೆ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ',
      'specialist_validated': 'ತಜ್ಞರಿಂದ ದೃಢೀಕರಿಸಲ್ಪಟ್ಟಿದೆ',

      // 3-Step Guided Flow Ribbon
      'step1_ribbon': '1. ರೋಗಿಯ ವಿವರಗಳು (Intake)',
      'step2_ribbon': '2. ರೆಟಿನಾ ಫೋಟೋ ತೆಗೆಯಿರಿ (Photo)',
      'step3_ribbon': '3. ಫಲಿತಾಂಶ ಮತ್ತು ಸ್ಲಿಪ್ (Result & Slip)',
      'step1_short': 'ವಿವರಗಳು',
      'step2_short': 'ಫೋಟೋ',
      'step3_short': 'ಫಲಿತಾಂಶ',

      // Navigation
      'nav_dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'nav_intake': 'ಹೊಸ ರೋಗಿ',
      'nav_patients': 'ರೋಗಿಗಳ ಪಟ್ಟಿ',
      'nav_sync': 'ಗ್ರಾಮೀಣ ಸಿಂಕ್',
      'nav_profile': 'ಪ್ರೊಫೈಲ್',
      'nav_queue': 'ಪರಿಶೀಲನಾ ಸಾಲು',
      'nav_cases': 'ಎಲ್ಲಾ ಪ್ರಕರಣಗಳು',
      'nav_overview': 'ಅವಲೋಕನ',
      'nav_reports': 'ವರದಿಗಳು',

      // Dashboard
      'greeting_morning': 'ಶುಭೋದಯ',
      'greeting_afternoon': 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
      'greeting_evening': 'ಶುಭ ಸಂಜೆ',
      'stat_screened': 'ಒಟ್ಟು ತಪಾಸಣೆ',
      'stat_screened_sub': 'ನೋಂದಾಯಿತ ರೋಗಿಗಳು',
      'stat_referable': 'ರೆಫರಲ್ ಅಗತ್ಯವಿದೆ',
      'stat_referable_sub': 'ವೈದ್ಯರಿಗೆ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ',
      'stat_pending': 'ಪರಿಶೀಲನೆ ಬಾಕಿ',
      'stat_pending_sub': 'ಸಾಲಿನಲ್ಲಿದೆ',
      'stat_completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
      'stat_completed_sub': 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
      'start_screening': '+ ಹೊಸ ರೆಟಿನಾ ತಪಾಸಣೆ ಪ್ರಾರಂಭಿಸಿ',
      'view_records': 'ದಾಖಲೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
      'recent_screenings': 'ಇತ್ತೀಚಿನ ತಪಾಸಣೆಗಳು',
      'view_all': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
      'quick_demo_test': '⚡ ಡೆಮೊ ಪರೀಕ್ಷಾ ಮಾದರಿಗಳು',
      'quick_demo_desc': 'ಕ್ಯಾಮೆರಾ ಇಲ್ಲದೆ ಮಾದರಿ ಚಿತ್ರಗಳನ್ನು ಪರೀಕ್ಷಿಸಿ',

      // Intake
      'patient_demographics': 'ರೋಗಿಯ ವಿವರಗಳು',
      'patient_id': 'ರೋಗಿ ID / ಟೋಕನ್ ಸಂಖ್ಯೆ',
      'age': 'ವಯಸ್ಸು (ವರ್ಷಗಳು)',
      'gender': 'ಲಿಂಗ',
      'gender_female': 'ಮಹಿಳೆ',
      'gender_male': 'ಪುರುಷ',
      'gender_other': 'ಇತರ',
      'diabetes_duration': 'ಮಧುಮೇಹದ ಅವಧಿ (ವರ್ಷಗಳು)',
      'eye_selection': 'ತಪಾಸಣೆಗೆ ಕಣ್ಣನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'right_eye': 'ಬಲಗಣ್ಣು (OD)',
      'left_eye': 'ಎಡಗಣ್ಣು (OS)',
      'od_subtitle': 'ಬಲಗಣ್ಣು • Oculus Dexter',
      'os_subtitle': 'ಎಡಗಣ್ಣು • Oculus Sinister',
      'proceed_capture': 'ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಲು ಮುಂದುವರಿಯಿರಿ',
      'fill_demo': '⚡ ಡೆಮೊ ರೋಗಿ ವಿವರ ಭರ್ತಿ ಮಾಡಿ',

      // Capture
      'retinal_acquisition': 'ರೆಟಿನಾ ಚಿತ್ರ ಸಂಗ್ರಹಣೆ',
      'camera_capture': 'ಕ್ಯಾಮೆರಾದಿಂದ ಫೋಟೋ ತೆಗೆಯಿರಿ',
      'gallery_select': 'ಫೈಲ್‌ನಿಂದ ಆಯ್ಕೆಮಾಡಿ',
      'reticle_guide': 'ಆಪ್ಟಿಕ್ ಡಿಸ್ಕ್ ಅನ್ನು ಮಧ್ಯದಲ್ಲಿರಿಸಿ',
      'loaded_guide': 'ಚಿತ್ರ ಲೋಡ್ ಆಗಿದೆ • ರೆಟಿನಾ ಪ್ರದೇಶ ಪರಿಶೀಲಿಸಿ',
      'clinical_samples_title': 'ಕ್ಲಿನಿಕಲ್ ಪರೀಕ್ಷಾ ಮಾದರಿಗಳು (SIH 2026 ಮಾನದಂಡ)',
      'confirm_quality': 'ಗುಣಮಟ್ಟವನ್ನು ದೃಢೀಕರಿಸಿ',
      'reset': 'ರೀಸೆಟ್',
      'optical_checklist_title': 'ಕ್ಯಾಮೆರಾ ಫೋಟೋ ಗುಣಮಟ್ಟ ಪರಿಶೀಲನೆ:',
      'chk_clarity': 'ಸ್ಪಷ್ಟತೆ: ಉತ್ತಮ',
      'chk_light': 'ಬೆಳಕು: ಸಾಕಷ್ಟು',
      'chk_center': 'ಕೇಂದ್ರ: ಸರಿಯಾಗಿದೆ',
      'speak_guidance': 'ರೋಗಿಗೆ ಧ್ವನಿ ಮಾರ್ಗದರ್ಶನ ನೀಡಿ',

      // Quality
      'quality_title': 'ಗುಣಮಟ್ಟ ಸುರಕ್ಷತಾ ಗೇಟ್',
      'sharpness': 'ಫೋಕಸ್ ಮತ್ತು ಸ್ಪಷ್ಟತೆ',
      'illumination': 'ಬೆಳಕು ಮತ್ತು ಹೊಳಪು',
      'fov': 'ವ್ಯಾಪ್ತಿ ಪ್ರದೇಶ',
      'quality_good': 'ಉತ್ತಮ ಗುಣಮಟ್ಟ',
      'quality_borderline': 'ಮಧ್ಯಮ ಗುಣಮಟ್ಟ (CLAHE ವರ್ಧಿತ)',
      'quality_ungradable': 'ಮಸುಕಾದ ಚಿತ್ರ — ದಯವಿಟ್ಟು ಮತ್ತೆ ಫೋಟೋ ತೆಗೆಯಿರಿ',
      'proceed_inference': 'AI ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ',
      'retake_image': 'ಮತ್ತೆ ಫೋಟೋ ತೆಗೆಯಿರಿ',

      // Results
      'ai_result_title': 'AI ನಿರ್ಧಾರ ಬೆಂಬಲ ಮೌಲ್ಯಮಾಪನ',
      'level_0': 'ಸಾಮಾನ್ಯ (ಯಾವುದೇ ಹಾನಿಯಿಲ್ಲ)',
      'level_1': 'ಸೌಮ್ಯ ಪರಿಣಾಮ (Mild NPDR)',
      'level_2': 'ಮಧ್ಯಮ ಪರಿಣಾಮ (Moderate NPDR)',
      'level_3': 'ತೀವ್ರ ಪರಿಣಾಮ (Severe NPDR)',
      'level_4': 'ಅತ್ಯಂತ ತೀವ್ರ ಪರಿಣಾಮ (ತುರ್ತು ರೆಫರಲ್)',
      'referable_yes': 'ಆಸ್ಪತ್ರೆ ರೆಫರಲ್ ಅಗತ್ಯವಿದೆ',
      'referable_no': 'ವಾರ್ಷಿಕ ತಪಾಸಣೆ ಸಾಕು',
      'view_xai': 'ಹೀಟ್‌ಮ್ಯಾಪ್ ವೀಕ್ಷಿಸಿ (Grad-CAM)',
      'view_report': 'ಸಂಪೂರ್ಣ ವರದಿ & ಸ್ಲಿಪ್ ವೀಕ್ಷಿಸಿ',
      'new_screening': 'ಮುಂದಿನ ರೋಗಿಯನ್ನು ಪರೀಕ್ಷಿಸಿ',
      'patient_slip_btn': 'ರೋಗಿ ರೆಫರಲ್ ಸ್ಲಿಪ್',

      // Explainability
      'xai_title': 'ದೃಶ್ಯ ವಿವರಣೆ (Grad-CAM ಹೀಟ್‌ಮ್ಯಾಪ್)',
      'tab_original': 'ಮೂಲ ಚಿತ್ರ',
      'tab_gradcam': 'ಹೀಟ್‌ಮ್ಯಾಪ್',
      'tab_overlay': 'ಓವರ್‌ಲೇ',
      'blend_opacity': 'ಹೀಟ್‌ಮ್ಯಾಪ್ ಪಾರದರ್ಶಕತೆ:',
      'lesion_guide_title': 'ರೆಟಿನಾ ಹಾನಿ ಮಾರ್ಗದರ್ಶಿ',
      'attended_structures': 'AI ಗುರುತಿಸಿದ ಪ್ರದೇಶಗಳು',

      // Report & Referral Slip
      'referral_card_title': 'ರೋಗಿ ರೆಫರಲ್ ಮತ್ತು ಸಲಹಾ ಕಾರ್ಡ್',
      'slip_title': 'ದೃಷ್ಟಿ — ಟೆಲಿ-ರೆಟಿನಾ ಸ್ಕ್ರೀನಿಂಗ್ ಮತ್ತು ರೆಫರಲ್ ಸ್ಲಿಪ್',
      'slip_subtitle': 'ರಾಷ್ಟ್ರೀಯ ಅಂಧತ್ವ ನಿಯಂತ್ರಣ ಕಾರ್ಯಕ್ರಮ (NPCB) ಬೆಂಬಲ | SIH 2026',
      'slip_verified_title': 'ಜಿಲ್ಲಾ ಟೆಲಿ-ನೇತ್ರಶಾಸ್ತ್ರದಿಂದ ದೃಢೀಕರಿಸಲ್ಪಟ್ಟಿದೆ',
      'slip_urgency_urgent': 'ನೇತ್ರ ತಜ್ಞರನ್ನು ತಕ್ಷಣ ಭೇಟಿ ಮಾಡಿ',
      'slip_urgency_routine': 'ದೃಷ್ಟಿಗೆ ಯಾವುದೇ ತಕ್ಷಣದ ಅಪಾಯವಿಲ್ಲ • ವಾರ್ಷಿಕ ತಪಾಸಣೆ ಸಾಕು',
      'slip_advice_urgent': 'ಆಸ್ಪತ್ರೆ ಸೂಚನೆ: ರೆಟಿನಾದಲ್ಲಿ ಮಧುಮೇಹದ ಬದಲಾವಣೆಗಳು ಕಂಡುಬಂದಿವೆ. ದಯವಿಟ್ಟು ಮುಂದಿನ 7-14 ದಿನಗಳಲ್ಲಿ ಜಿಲ್ಲಾ ನೇತ್ರ ತಜ್ಞರನ್ನು ಭೇಟಿ ಮಾಡಿ.',
      'slip_advice_routine': 'ಸಲಹೆ: ಪ್ರಸ್ತುತ ಯಾವುದೇ ಗಂಭೀರ ಹಾನಿಯಿಲ್ಲ. ರಕ್ತದಲ್ಲಿನ ಸಕ್ಕರೆಯನ್ನು ನಿಯಂತ್ರಣದಲ್ಲಿಟ್ಟುಕೊಳ್ಳಿ ಮತ್ತು 12 ತಿಂಗಳ ನಂತರ ಮತ್ತೆ ತಪಾಸಣೆ ಮಾಡಿಸಿ.',
      'slip_tips_title': 'ರೋಗಿ ಮತ್ತು ಕುಟುಂಬಕ್ಕಾಗಿ ಪ್ರಮುಖ ಆರೋಗ್ಯ ಮಾರ್ಗದರ್ಶನ:',
      'slip_tip1_title': '1. ರಕ್ತದಲ್ಲಿನ ಸಕ್ಕರೆ ನಿಯಂತ್ರಣ (HbA1c < 7.0%)',
      'slip_tip1_desc': 'ಔಷಧಿಗಳನ್ನು ನಿಯಮಿತವಾಗಿ ತೆಗೆದುಕೊಳ್ಳಿ. 3 ತಿಂಗಳ ಸರಾಸರಿ HbA1c 7% ಕ್ಕಿಂತ ಕಡಿಮೆ ಇರಿಸಿ.',
      'slip_tip2_title': '2. ರಕ್ತದೊತ್ತಡ ನಿಯಂತ್ರಣ (< 130/80 mmHg)',
      'slip_tip2_desc': 'ಅಧಿಕ ರಕ್ತದೊತ್ತಡ ಕಣ್ಣಿನ ರಕ್ತನಾಳಗಳನ್ನು ಹಾನಿಗೊಳಿಸುತ್ತದೆ.',
      'slip_tip3_title': '3. ಸಮತೋಲಿತ ಕಡಿಮೆ ಸಕ್ಕರೆ ಆಹಾರ',
      'slip_tip3_desc': 'ಹಸಿರು ತರಕಾರಿಗಳು, ಕಡಿಮೆ ಎಣ್ಣೆ ಮತ್ತು ಸಾಕಷ್ಟು ನೀರು ಕುಡಿಯಿರಿ. ಸಕ್ಕರೆಯನ್ನು ತಪ್ಪಿಸಿ.',
      'slip_tip4_title': '4. ನಿಯಮಿತ ರೆಟಿನಾ ತಪಾಸಣೆ',
      'slip_tip4_desc': 'ಆರಂಭದಲ್ಲಿ ಯಾವುದೇ ಲಕ್ಷಣಗಳು ಇರುವುದಿಲ್ಲ. ನಿಯಮಿತ ತಪಾಸಣೆಯೇ ದೃಷ್ಟಿ ರಕ್ಷಿಸುತ್ತದೆ.',
      'slip_footer_doc': 'ದೃಢೀಕೃತ ಟೆಲಿ-ನೇತ್ರತಜ್ಞ: ಡಾ. ರಾಜೇಶ್ ಕುಮಾರ್, MD (ನೇತ್ರಶಾಸ್ತ್ರ)',
      'slip_footer_notice': '*ಇದು ಕಂಪ್ಯೂಟರೀಕೃತ ಟೆಲಿ-ಸ್ಕ್ರೀನಿಂಗ್ ಸ್ಲಿಪ್, ಭೌತಿಕ ಸಹಿಯ ಅಗತ್ಯವಿಲ್ಲ.',
      'slip_qr_label': 'QR ಪರಿಶೀಲನೆ',
      'slip_print_btn': 'ಸ್ಲಿಪ್ ಪ್ರಿಂಟ್ ಮಾಡಿ',
      'slip_share_btn': 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಕಳುಹಿಸಿ',
      'urgency_immediate': 'ತುರ್ತು: 7–14 ದಿನಗಳಲ್ಲಿ ನೇತ್ರ ತಜ್ಞರನ್ನು ಭೇಟಿ ಮಾಡಿ',
      'urgency_routine': 'ಸಾಮಾನ್ಯ: 12 ತಿಂಗಳಲ್ಲಿ ವಾರ್ಷಿಕ ತಪಾಸಣೆ',
      'advice_hba1c': 'HbA1c 7.0% ಕ್ಕಿಂತ ಕಡಿಮೆ ಇರಿಸಿ',
      'advice_bp': 'ರಕ್ತದೊತ್ತಡವನ್ನು ನಿಯಂತ್ರಣದಲ್ಲಿಡಿ (< 130/80)',
      'advice_diet': 'ಕಡಿಮೆ ಸಕ್ಕರೆ ಸಮತೋಲಿತ ಆಹಾರ ಸೇವಿಸಿ',
      'print_pdf': 'PDF ಸ್ಲಿಪ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
      'share_slip': 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ',
    },
  };

  static String tr(String key, String langCode) {
    final langMap = _localizedValues[langCode] ?? _localizedValues['en']!;
    return langMap[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
